/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AchievementCategoryData {
  color: string;
  icon: string;
  id: Generated<number>;
  nameId: number;
  order: number;
  parentId: number;
  visibilityCriterion: string;
}

export interface AchievementCategoryDataAchievementIdsJunction {
  AchievementCategoryData_id: number | null;
  target_id: number | null;
}

export interface AchievementData {
  accountLinked: number;
  categoryId: number;
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  level: number;
  nameId: number;
  order: number;
  points: number;
}

export interface AchievementDataObjectiveIdsJunction {
  AchievementData_id: number | null;
  target_id: number | null;
}

export interface AchievementDataRewardIdsJunction {
  AchievementData_id: number | null;
  target_id: number | null;
}

export interface AchievementObjectiveData {
  achievementId: number;
  criterion: string;
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface AchievementRewardData {
  achievementId: number;
  alterationsReward: string;
  criterions: string;
  emotesReward: string;
  experienceRatio: number;
  guildPoints: number;
  id: Generated<number>;
  itemsQuantityReward: string;
  itemsReward: string;
  kamasRatio: number;
  kamasScaleWithPlayerLevel: number;
  ornamentsReward: string;
  spellsReward: string;
  titlesReward: string;
}

export interface ActionFilterData {
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface ActivitySuggestionCategoryData {
  id: Generated<number>;
  nameId: number;
  parentId: number;
}

export interface ActivitySuggestionData {
  categoryId: number;
  descriptionId: number;
  endDate: number;
  icon: string;
  iconCategoryId: number;
  id: Generated<number>;
  isLarge: number;
  level: number;
  mapId: number;
  nameId: number;
  startDate: number;
}

export interface AlignmentGiftData {
  id: Generated<number>;
  nameId: number;
}

export interface AlignmentOrderData {
  id: Generated<number>;
  nameId: number;
  sideId: number;
}

export interface AlignmentRankData {
  descriptionId: number;
  id: Generated<number>;
  minimumAlignment: number;
  nameId: number;
  orderId: number;
}

export interface AlignmentRankGiftsData {
  gifts: string;
  id: Generated<number>;
}

export interface AlignmentSideData {
  id: Generated<number>;
  nameId: number;
}

export interface AlignmentTitleData {
  id: string;
  namesId: string;
  shortsId: string;
  sideId: number;
}

export interface AllianceRankData {
  gfxId: number;
  id: Generated<number>;
  isModifiable: number;
  nameId: number;
  order: number;
}

export interface AllianceRankNameSuggestionData {
  id: string;
  uiKey: string;
}

export interface AllianceRightData {
  groupId: number;
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface AllianceRightGroupData {
  id: Generated<number>;
  nameId: number;
  order: number;
  rights: string;
}

export interface AllianceTagData {
  id: Generated<number>;
  nameId: number;
  order: number;
  typeId: number;
}

export interface AllianceTagTypeData {
  id: Generated<number>;
  nameId: number;
}

export interface AlmanaxCalendarData {
  categoryId: number;
  celebrationDescriptionId: number;
  celebrationNameId: number;
  dates: string;
  descId: number;
  id: Generated<number>;
  meridiaDescriptionId: number;
  meridiaEffectId: number;
  meridiaIllustrationId: number;
  nameId: number;
  npcId: number;
  objectiveId: number;
  rubrikabraxId: number;
}

export interface AlmanaxCalendarDataBonusesIdsJunction {
  AlmanaxCalendarData_id: number | null;
  target_id: number | null;
}

export interface AlmanaxCategoryData {
  id: Generated<number>;
  nameId: number;
  protectorDescriptionId: number;
  protectorIllustrationId: number;
  protectorNameId: number;
}

export interface AlmanaxZodiacData {
  dateEnd: string;
  dateStart: string;
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
  picture: string;
}

export interface AlterationCategoryData {
  id: Generated<number>;
  nameId: number;
  parentId: number;
}

export interface AlterationData {
  categoryId: number;
  criterions: string;
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  isVisible: number;
  isWebDisplay: number;
  nameId: number;
  possibleEffects: string;
}

export interface AppearanceData {
  data: string;
  id: Generated<number>;
  type: number;
  usePlayerLook: number;
}

export interface AreaData {
  bounds: string;
  containHouses: number;
  containPaddocks: number;
  hasSuggestion: number;
  hasWorldMap: number;
  id: Generated<number>;
  nameId: number;
  superAreaId: number;
  worldmapId: number;
}

export interface AreaDataSubareaIdsJunction {
  AreaData_id: number | null;
  target_id: number | null;
}

export interface ArenaLeagueData {
  highRatingBound: number;
  icon: string;
  id: Generated<number>;
  illus: string;
  isLastLeague: number;
  lowRatingBound: number;
  nameId: number;
  ornamentId: number;
}

export interface ArenaLeagueSeasonData {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number;
  uid: number;
}

export interface AuctionHouseData {
  allowedQuantities: string;
  id: Generated<number>;
  typeId: number;
}

export interface BodyData {
  assetId: string;
  availableAtCreation: number;
  breed: number;
  gender: number;
  id: Generated<number>;
  label: string;
  nameId: number;
  order: number;
  payable: number;
  skins: string;
}

export interface BonusCriterionData {
  id: Generated<number>;
  type: number;
  value: number;
}

export interface BonusData {
  amount: number;
  id: Generated<number>;
  type: number;
}

export interface BonusDataCriterionsIdsJunction {
  BonusData_id: number | null;
  target_id: number | null;
}

export interface BreachBossData {
  accessCriterion: string;
  apparitionCriterion: string;
  category: number;
  id: Generated<number>;
  incompatibleBosses: string;
  monsterId: number;
  rewardId: number;
}

export interface BreachDungeonModificatorData {
  additionalRewardPercent: number;
  criterion: string;
  id: Generated<number>;
  isPositiveForPlayers: number;
  modificatorId: number;
  score: number;
  tooltipBaseline: string;
}

export interface BreachPrizeData {
  categoryId: number;
  descriptionKey: string;
  id: Generated<number>;
  nameId: number;
  tooltipKey: string;
}

export interface BreachWorldMapCoordinateData {
  exploredMapIcon: number;
  id: string;
  mapCoordinateX: number;
  mapCoordinateY: number;
  mapStage: number;
  unexploredMapIcon: number;
}

export interface BreachWorldMapSectorData {
  id: Generated<number>;
  legendId: string;
  maxStage: number;
  minStage: number;
  sectorIcon: string;
  sectorNameId: string;
}

export interface BreedData {
  breedRoles: string;
  breedSpellsId: string;
  complexity: number;
  creatureBonesId: number;
  descriptionId: number;
  femaleColors: string;
  femaleLook: string;
  gameplayDescriptionId: string;
  id: Generated<number>;
  maleColors: string;
  maleLook: string;
  shortNameId: string;
  sortIndex: number;
  statsPointsForAgility: string;
  statsPointsForChance: string;
  statsPointsForIntelligence: string;
  statsPointsForStrength: string;
  statsPointsForVitality: string;
  statsPointsForWisdom: string;
}

export interface BreedRoleData {
  assetId: number;
  color: number;
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
}

export interface CalendarEventData {
  categoryId: number;
  criterion: string;
  descriptionId: number;
  id: Generated<number>;
  map: number;
  nameId: number;
  picture: string;
  recommendedLevel: number;
  rewards: string;
}

export interface CardBackgroundData {
  id: Generated<number>;
  isDefault: number;
  nameId: number;
  picture: string;
}

export interface ChallengeData {
  activationCriterion: string;
  categoryId: number;
  completionCriterion: string;
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  incompatibleChallenges: string;
  nameId: number;
  targetMonsterId: number;
}

export interface CharacteristicCategoryData {
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface CharacteristicCategoryDataCharacteristicIdsJunction {
  CharacteristicCategoryData_id: number | null;
  target_id: number | null;
}

export interface CharacteristicData {
  asset: string;
  categoryId: number;
  id: Generated<number>;
  keyword: string;
  nameId: number;
  order: number;
  scaleFormulaId: number;
  upgradable: number;
  visible: number;
}

export interface CharacterXpMappingData {
  experiencePoints: number;
  id: string;
}

export interface ChatChannelData {
  descriptionId: number;
  id: Generated<number>;
  isPrivate: number;
  nameId: number;
  shortcut: string;
}

export interface ChoiceData {
  choiceNameId: number;
  duration: number;
  id: Generated<number>;
  options: string;
  parentId: number;
}

export interface CollectableData {
  entityId: number;
  gfxId: number;
  id: string;
  name: string;
  order: number;
  rarity: number;
  typeId: number;
}

export interface CollectionData {
  collectables: string;
  criterion: string;
  id: string;
  name: string;
  typeId: number;
}

export interface CompanionCharacteristicData {
  caracId: number;
  companionId: number;
  id: Generated<number>;
  order: number;
  statPerLevelRange: string;
}

export interface CompanionData {
  assetId: number;
  characteristics: string;
  creatureBoneId: number;
  descriptionId: number;
  id: Generated<number>;
  look: string;
  nameId: number;
  spells: string;
  startingSpellLevelId: number;
  visibility: string;
  webDisplay: number;
}

export interface CompanionSpellData {
  companionId: number;
  gradeByLevel: string;
  id: Generated<number>;
  spellId: number;
}

export interface ConstantData {
  id: Generated<number>;
  value: string;
}

export interface CreatureBoneOverrideData {
  boneId: number;
  creatureBoneId: number;
  id: string;
}

export interface CreatureBoneTypeData {
  creatureBoneId: number;
  id: Generated<number>;
}

export interface CustomModeBreedSpellData {
  breedId: number;
  id: Generated<number>;
  isHidden: number;
  isInitialSpell: number;
  pairId: number;
}

export interface DocumentData {
  authorId: string;
  clientProperties: string;
  contentCSS: string;
  contentId: string;
  id: Generated<number>;
  showBackgroundImage: number;
  showTitle: number;
  subTitleId: string;
  titleId: string;
  typeId: number;
}

export interface DofusProgressionData {
  backgroundColor: string;
  descriptionId: number;
  gfxId: string;
  id: Generated<number>;
  isEvent: number;
  isPrimordial: number;
  maxLevel: number;
  minLevel: number;
  nameId: number;
  order: number;
  prerequisites: string;
  steps: string;
}

export interface DungeonData {
  achievements: string;
  availableInAutomaticGroupSearch: number;
  availableInLobby: number;
  availableOnKeyring: number;
  bosses: string;
  difficulty: number;
  entranceMapId: number;
  exitMapId: number;
  id: Generated<number>;
  minLevel: number;
  nameId: number;
  optimalPlayerLevel: number;
  requiredObjects: string;
}

export interface DungeonDataMapIdsJunction {
  DungeonData_id: number | null;
  target_id: number | null;
}

export interface EffectData {
  actionFiltersId: string;
  active: number;
  bonusType: number;
  boost: number;
  category: number;
  characteristic: number;
  characteristicOperator: string;
  descriptionId: number;
  effectPowerRate: number;
  effectPriority: number;
  effectTriggerDuration: number;
  elementId: number;
  forceMinMax: number;
  hideValueInTooltip: number;
  iconId: number;
  id: Generated<number>;
  isInPercent: number;
  oppositeId: number;
  parametersFixed: number;
  showInSet: number;
  showInTooltip: number;
  textIconReferenceId: number;
  theoreticalDescriptionId: string;
  theoreticalPattern: number;
  useDice: number;
  useInFight: number;
}

export interface EffectInstanceDice {
  baseEffectId: number;
  delay: number;
  diceNum: number;
  diceSide: number;
  dispellable: number;
  displayZero: number;
  duration: number;
  effectElement: number;
  effectId: number;
  effectTriggerDuration: number;
  effectUid: number;
  group: number;
  id: string;
  m_flags: number;
  modificator: number;
  order: number;
  random: number;
  source: string;
  spellId: number;
  targetId: number;
  targetMask: string;
  triggers: string;
  value: number;
  zoneDescr: string;
}

export interface EmblemBackgroundData {
  id: Generated<number>;
  order: number;
}

export interface EmblemSymbolCategoryData {
  id: Generated<number>;
  nameId: number;
}

export interface EmblemSymbolData {
  categoryId: number;
  colorizable: number;
  iconId: number;
  id: Generated<number>;
  order: number;
  skinId: number;
}

export interface EmoticonData {
  allowOnMount: number;
  animName: string;
  aura: number;
  cooldown: number;
  criterion: string;
  duration: number;
  eightDirections: number;
  id: Generated<number>;
  nameId: number;
  order: number;
  persistancy: number;
  persistantAnimName: string;
  scale: number;
  shortcutId: string;
  spellLevelId: number;
  weight: number;
}

export interface EvolutiveEffectData {
  actionId: number;
  id: Generated<number>;
  progressionPerLevelRange: string;
  targetId: number;
}

export interface EvolutiveItemTypeData {
  experienceBoost: number;
  experienceByLevel: string;
  id: Generated<number>;
  maxLevel: number;
}

export interface ExpeditionSeasonData {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number;
  uid: number;
}

export interface ExternalNotificationData {
  categoryId: number;
  colorId: number;
  defaultEnable: number;
  defaultMultiAccount: number;
  defaultNotify: number;
  defaultSound: number;
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  messageId: string;
  name: string;
}

export interface FeatureDescriptionData {
  children: string;
  criterion: string;
  descriptionId: number;
  id: Generated<number>;
  images: string;
  nameId: number;
  parentId: number;
  priority: number;
}

export interface FightScenarioData {
  id: Generated<number>;
  nameId: string;
}

export interface ForgettableSpellData {
  id: Generated<number>;
  itemId: number;
  pairId: number;
}

export interface GuildChestTabData {
  cost: number;
  dropRight: number;
  gfxId: number;
  id: string;
  index: number;
  nameId: number;
  openRight: number;
  seniority: number;
  serverType: number;
  tabId: number;
  takeRight: number;
}

export interface GuildHallData {
  id: Generated<number>;
  mapId: number;
  nameId: number;
  subareaId: number;
}

export interface GuildHallThemeData {
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface GuildLevelRewardData {
  descriptionId: number;
  id: string;
  level: number;
  nameId: number;
  picto: string;
}

export interface GuildMissionActivityData {
  id: Generated<number>;
  level: number;
  nameId: number;
  recommendedPlayers: number;
  rerollCost: number;
}

export interface GuildMissionActivityDataMilestonesIdsJunction {
  GuildMissionActivityData_id: number | null;
  target_id: number | null;
}

export interface GuildMissionData {
  activityPoint: number;
  categoryId: number;
  gradeId: number;
  id: Generated<number>;
  nameId: number;
  objectives: string;
  rankId: number;
  recommendedLevel: number;
  superCategoryId: number;
  token: number;
}

export interface GuildMissionGradeData {
  activityPoint: number;
  id: Generated<number>;
  name: string;
  rankId: number;
  token: number;
}

export interface GuildMissionMilestoneData {
  acknowledgmentPoint: number;
  activityId: number;
  activityPoint: number;
  id: Generated<number>;
  milestoneLevel: number;
  nameId: number;
  xp: number;
}

export interface GuildMissionObjectiveData {
  activationCriterion: string;
  alterationId: number;
  areaId: number;
  descriptionId: number;
  familyId: number;
  familyMonsters: string;
  id: Generated<number>;
  inDungeon: number;
  intensity: number;
  mapId: number;
  minLevel: number;
  missionId: number;
  monsterId: number;
  objectId: number;
  order: number;
  quantity: number;
  quests: string;
  seedId: number;
  stage: number;
  subareaId: number;
  superCategoryId: number;
}

export interface GuildMissionRankData {
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
}

export interface GuildMissionSuperCategoryData {
  id: Generated<number>;
  nameId: number;
}

export interface GuildRaidData {
  canFinish: number;
  canRestart: number;
  descriptionId: number;
  duration: number;
  goals: string;
  groups: string;
  id: Generated<number>;
  maxPlayers: number;
  maxScore: number;
  minPlayers: number;
  nameId: number;
  playerHealth: number;
  price: number;
  type: number;
  variables: string;
}

export interface GuildRaidsGoalData {
  id: Generated<number>;
  impactProgress: number;
  nameId: number;
  raidId: number;
  requisiteForDisplay: string;
  score: number;
  value: number;
}

export interface GuildRaidsGroupData {
  descriptionId: number;
  id: Generated<number>;
  maxPlayers: number;
  minPlayers: number;
  nameId: number;
  raidId: number;
}

export interface GuildRaidsLaddersRewardData {
  guildExperience: number;
  id: Generated<number>;
  items: string;
  order: number;
  ornaments: string;
  percentage: number;
  position: string;
  raidId: number;
  titles: string;
}

export interface GuildRaidsReward {
  descriptionId: number;
  experience: number;
  id: Generated<number>;
  kamas: number;
  order: number;
  raidId: number;
  rewards: string;
  score: number;
}

export interface GuildRankData {
  gfxId: number;
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface GuildRankNameSuggestionData {
  id: string;
  uiKey: string;
}

export interface GuildRightData {
  groupId: number;
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface GuildRightGroupData {
  id: Generated<number>;
  nameId: number;
  order: number;
  rights: string;
}

export interface GuildShopBoostData {
  alterationId: number;
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
}

export interface GuildTagData {
  id: Generated<number>;
  nameId: number;
  order: number;
  typeId: number;
}

export interface GuildTagTypeData {
  id: Generated<number>;
  nameId: number;
}

export interface HavenbagFurnitureData {
  blocksMovement: number;
  cellsHeight: number;
  cellsWidth: number;
  color: number;
  elementId: number;
  gfxId: number;
  height: number;
  horizontalSymmetry: number;
  id: string;
  isStackable: number;
  layerId: number;
  order: number;
  origin: string;
  size: string;
  skillId: number;
  themeId: number;
  typeId: number;
}

export interface HavenbagThemeData {
  id: Generated<number>;
  mapId: number;
  nameId: number;
}

export interface HeadData {
  assetId: string;
  availableAtCreation: number;
  breed: number;
  gender: number;
  id: Generated<number>;
  label: string;
  nameId: number;
  order: number;
  payable: number;
  skins: string;
}

export interface HintCategoryData {
  id: Generated<number>;
  nameId: number;
}

export interface HintData {
  categoryId: number;
  gfx: number;
  id: Generated<number>;
  level: number;
  mapId: number;
  nameId: number;
  outdoor: number;
  realMapId: number;
  subareaId: number;
  worldMapId: number;
  x: number;
  y: number;
}

export interface HouseData {
  defaultPrice: number;
  descriptionId: number;
  gfxId: number;
  id: string;
  nameId: number;
  roomCount: number;
  typeId: number;
}

export interface IdleData {
  animationKey: string;
  breed: number;
  criterion: string;
  iconIdFemale: string;
  iconIdMale: string;
  id: string;
  known: number;
  nameId: number;
  order: number;
}

export interface InfiniteDreamIntensityData {
  additionalLife: number;
  dreamFragments: number;
  dropBonus: number;
  droplegend: number;
  id: Generated<number>;
  intensity: number;
  money: number;
  nameId: number;
  xpBonus: number;
}

export interface InfiniteDreamRewardActionData {
  duration: number;
  effect: string;
  id: Generated<number>;
  isAlly: number;
}

export interface InfiniteDreamRewardData {
  actions: string;
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
}

export interface InfiniteDreamTrialData {
  achievementId: number;
  achievementIntensity: number;
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
  picture: string;
  seed: string;
}

export interface InfoMessageData {
  id: string;
  messageId: number;
  textId: number;
  typeId: number;
}

export interface InteractiveData {
  id: Generated<number>;
  nameId: number;
}

export interface ItemData {
  appearanceId: number;
  craftConditionalCriterion: string;
  craftFeasibleCriterion: string;
  craftVisibleCriterion: string;
  craftXpRatio: number;
  criterions: string;
  criterionsTarget: string;
  descriptionId: number;
  favoriteRecyclingSubareas: string;
  favoriteSubAreas: string;
  favoriteSubAreasBonus: number;
  iconId: number;
  id: Generated<number>;
  importantNoticeId: string;
  isColorable: number;
  itemSetId: number;
  level: number;
  m_flags: number;
  nameId: number;
  possibleEffects: string;
  price: number;
  realWeight: number;
  recipeSlots: number;
  recyclingNuggets: number;
  resourcesBySubarea: string;
  typeId: number;
  visibilityCriterion: string;
}

export interface ItemDataDropMonsterIdsJunction {
  ItemData_id: number | null;
  target_id: number | null;
}

export interface ItemDataDropTemporisMonsterIdsJunction {
  ItemData_id: number | null;
  target_id: number | null;
}

export interface ItemDataEvolutiveEffectIdsJunction {
  ItemData_id: number | null;
  target_id: number | null;
}

export interface ItemDataRecipeIdsJunction {
  ItemData_id: number | null;
  target_id: number | null;
}

export interface ItemSetData {
  bonusIsSecret: number;
  effects: string;
  id: Generated<number>;
  isCosmetic: number;
  items: string;
  nameId: number;
}

export interface ItemSuperTypeData {
  id: Generated<number>;
  possiblePositions: string;
}

export interface ItemTypeData {
  categoryId: number;
  craftXpRatio: number;
  evolutiveTypeId: number;
  id: Generated<number>;
  isInEncyclopedia: number;
  nameId: number;
  rawZone: string;
  superTypeId: number;
}

export interface JobData {
  hasLegendaryCraft: number;
  iconId: number;
  id: Generated<number>;
  nameId: number;
}

export interface KothRoleData {
  id: Generated<number>;
  isDefault: number;
  nameId: number;
}

export interface LegendaryPowerCategoryData {
  categoryName: string;
  categoryOverridable: number;
  categorySpells: string;
  id: Generated<number>;
}

export interface LegendaryTreasureHuntData {
  chestId: number;
  id: Generated<number>;
  level: number;
  mapItemId: number;
  monsterId: number;
  nameId: number;
  xpRatio: number;
}

export interface LivingObjectSkinMoodsData {
  id: string;
  moods: string;
  skinId: number;
}

export interface LobbyTagData {
  concurrentTags: string;
  id: Generated<number>;
  nameId: number;
}

export interface LobbyTypeData {
  id: Generated<number>;
  maxMember: number;
  minMember: number;
  nameId: number;
  tags: string;
}

export interface LuaFormulaData {
  formula: string;
  id: string;
}

export interface MapInformationData {
  id: Generated<number>;
  m_flags: number;
  nameId: number;
  posX: number;
  posY: number;
  subAreaId: number;
  tacticalModeTemplateId: number;
  worldMap: number;
}

export interface MapReferenceData {
  cellId: number;
  id: Generated<number>;
  mapId: number;
}

export interface MapsCoordinateData {
  compressedCoords: number;
  id: string;
}

export interface MapsCoordinateDataMapIdsJunction {
  MapsCoordinateData_id: number | null;
  target_id: number | null;
}

export interface MapScrollActionData {
  bottomExists: number;
  bottomMapId: number;
  id: Generated<number>;
  leftExists: number;
  leftMapId: number;
  rightExists: number;
  rightMapId: number;
  topExists: number;
  topMapId: number;
}

export interface ModsterData {
  id: Generated<number>;
  itemId: number;
  modsterAchievements: string;
  modsterActiveSpells: string;
  modsterHiddenAchievements: string;
  modsterId: number;
  modsterPassiveSpells: string;
  order: number;
  parentsModsterId: string;
}

export interface MonsterData {
  aggressiveAttackDelay: number;
  aggressiveImmunityCriterion: string;
  aggressiveLevelDiff: number;
  aggressiveZoneSize: number;
  animFunList: string;
  characRatios: string;
  correspondingMiniBossId: number;
  creatureBoneId: number;
  drops: string;
  favoriteSubareaId: number;
  gfxId: number;
  globalDrops: string;
  grades: string;
  id: Generated<number>;
  incompatibleChallenges: string;
  incompatibleIdols: string;
  isBounty: number;
  look: string;
  m_flags: number;
  nameId: number;
  race: number;
  scaleGradeRef: number;
  souls: string;
  speedAdjust: number;
  spellGrades: string;
  spells: string;
  subareas: string;
  summonCost: number;
  temporisDrops: string;
}

export interface MonsterMiniBossData {
  id: Generated<number>;
  monsterReplacingId: number;
}

export interface MonsterRaceData {
  aggressiveAttackDelay: number;
  aggressiveImmunityCriterion: string;
  aggressiveLevelDiff: number;
  aggressiveZoneSize: number;
  id: Generated<number>;
  monsters: string;
  nameId: number;
  superRaceId: number;
}

export interface MonsterSuperRaceData {
  id: Generated<number>;
  nameId: number;
}

export interface MonthData {
  id: string;
  nameId: number;
}

export interface MountBehaviorData {
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
}

export interface MountBoneData {
  id: Generated<number>;
}

export interface MountData {
  certificateId: number;
  effects: string;
  familyId: number;
  id: Generated<number>;
  look: string;
  nameId: number;
}

export interface MountFamilyData {
  headUri: string;
  id: Generated<number>;
  nameId: number;
}

export interface NamingRuleData {
  id: Generated<number>;
  maxLength: number;
  minLength: number;
  regexp: string;
}

export interface NotificationData {
  cantBeClosed: number;
  iconId: number;
  id: Generated<number>;
  messageId: string;
  titleId: string;
  trigger: string;
  typeId: number;
}

export interface NpcActionData {
  id: Generated<number>;
  nameId: number;
  realId: number;
}

export interface NpcData {
  actions: string;
  animFunList: string;
  defaultSkinId: number;
  dialogData: string;
  dialogMessages: string;
  dialogReplies: string;
  fastAnimsFun: number;
  gender: number;
  id: Generated<number>;
  look: string;
  nameId: number;
  tooltipVisible: number;
}

export interface NpcDialogSkinData {
  backgroundColor: string;
  borderColor: string;
  buttonsColorTypes: number;
  fontColor: string;
  gfxId: number;
  hasHalo: number;
  headerColor: string;
  headerDecorationColor: string;
  headerDecorationGfxId: number;
  headerFontColor: string;
  headerGfxId: number;
  headerOrnamentColor: string;
  headerOrnamentGfxId: number;
  id: Generated<number>;
  isBold: number;
}

export interface NpcMessageData {
  id: Generated<number>;
  messageBubblePosition: number;
  messageId: string;
  messageNpcMoodId: number;
  messageParams: string;
  messageSkinId: number;
}

export interface OptionalFeatureData {
  activationCriterions: string;
  id: Generated<number>;
  isActivationOnLaunch: number;
  isActivationOnServerConnection: number;
  isClient: number;
  isServer: number;
  keyword: string;
}

export interface OrnamentData {
  assetId: number;
  iconId: number;
  id: Generated<number>;
  nameId: number;
  order: number;
  visible: number;
}

export interface PaddockGaugesData {
  id: Generated<number>;
  name: string;
  tierMaxValues: string;
}

export interface PaddocksData {
  id: Generated<number>;
  nameId: number;
}

export interface PointOfInterestData {
  id: Generated<number>;
  nameId: number;
}

export interface PopupInformationData {
  autoTrigger: number;
  buttons: string;
  cacheType: number;
  criterion: string;
  descriptionId: number;
  headerId: string;
  id: Generated<number>;
  illuName: string;
  parentId: number;
  titleId: string;
}

export interface PresetIconData {
  id: Generated<number>;
}

export interface ProgressingAchievementSeasonData {
  id: Generated<number>;
  name: string;
  seasonId: number;
}

export interface ProgressingAchievementStepData {
  achievementId: number;
  id: Generated<number>;
  isBuyable: number;
  isCosmetic: number;
  progressId: number;
  score: number;
}

export interface QuestCategoryData {
  id: Generated<number>;
  nameId: number;
  order: number;
}

export interface QuestCategoryDataQuestIdsJunction {
  QuestCategoryData_id: number | null;
  target_id: number | null;
}

export interface QuestData {
  categoryId: number;
  followable: number;
  id: Generated<number>;
  isDungeonQuest: number;
  isEvent: number;
  isPartyQuest: number;
  levelMax: number;
  levelMin: number;
  nameId: number;
  repeatLimit: number;
  repeatType: number;
  startCriterion: string;
  startPosition: string;
  type: number;
}

export interface QuestDataStepIdsJunction {
  QuestData_id: number | null;
  target_id: number | null;
}

export interface QuestObjectiveBringItemToNpcData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveBringSoulToNpcData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveCraftItemData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveDiscoverMapData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveDiscoverSubAreaData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFightMonsterData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFightMonstersOnMapData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFreeFormData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveGoToNpcData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveMultiFightMonsterData {
  coords: string;
  dialogId: number;
  id: Generated<number>;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveTypeData {
  id: Generated<number>;
  nameId: number;
}

export interface QuestStepData {
  descriptionId: number;
  dialogId: number;
  duration: number;
  id: Generated<number>;
  nameId: number;
  optimalLevel: number;
  questId: number;
}

export interface QuestStepDataObjectiveIdsJunction {
  QuestStepData_id: number | null;
  target_id: number | null;
}

export interface QuestStepDataRewardsIdsJunction {
  QuestStepData_id: number | null;
  target_id: number | null;
}

export interface QuestStepRewardData {
  emotesReward: string;
  experienceRatio: number;
  id: Generated<number>;
  itemsReward: string;
  jobsReward: string;
  kamasRatio: number;
  kamasScaleWithPlayerLevel: number;
  levelMax: number;
  levelMin: number;
  spellsReward: string;
  stepId: number;
  titlesReward: string;
}

export interface RandomDropGroupData {
  displayChances: number;
  id: Generated<number>;
  randomDropItems: string;
}

export interface RecipeData {
  id: string;
  jobId: number;
  quantities: string;
  resultId: number;
  resultLevel: number;
  resultNameId: string;
  resultTypeId: number;
  skillId: number;
}

export interface RecipeDataIngredientIdsJunction {
  RecipeData_id: number | null;
  target_id: number | null;
}

export interface RideFoodData {
  familyId: number;
  gid: number;
  id: string;
  typeId: number;
}

export interface RideGaugesData {
  id: Generated<number>;
  maxMood: number;
  maxValue: number;
  minMood: number;
}

export interface RiderBoneData {
  id: Generated<number>;
}

export interface RidesData {
  breedingExperienceRewardQuantity: number;
  breedingTokenRewardQuantity: number;
  children: string;
  colorId: number;
  extractionRewardQuantity: number;
  generation: number;
  geneticWeight: number;
  id: Generated<number>;
  linkedItemGid: number;
  nameId: number;
  parents: string;
  senileExtractionRewardQuantity: number;
  speciesId: number;
}

export interface RideSpeciesData {
  extractionRewardGid: number;
  id: Generated<number>;
  nameId: number;
}

export interface ServerCommunityData {
  defaultCountries: string;
  id: Generated<number>;
  nameId: number;
  namingRuleAdminId: number;
  namingRuleAllianceNameId: number;
  namingRuleAllianceTagId: number;
  namingRuleGuildNameId: number;
  namingRuleModoId: number;
  namingRuleMountNameId: number;
  namingRuleNameGeneratorId: number;
  namingRulePartyNameId: number;
  namingRulePlayerNameId: number;
  namingRulePresetNameId: number;
  shortId: string;
}

export interface ServerCommunityDataSupportedLangIdsJunction {
  ServerCommunityData_id: number | null;
  target_id: number | null;
}

export interface ServerData {
  commentId: string;
  communityId: number;
  gameTypeId: number;
  id: Generated<number>;
  illus: string;
  language: string;
  monoAccount: number;
  nameId: number;
  populationId: number;
}

export interface ServerGameTypeData {
  descriptionId: number;
  id: Generated<number>;
  nameId: number;
  rulesId: number;
  selectableByPlayer: number;
}

export interface ServerLangData {
  id: Generated<number>;
  langCode: string;
  nameId: number;
}

export interface ServerPopulationData {
  id: Generated<number>;
  nameId: number;
  weight: number;
}

export interface ServerSeasonData {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number;
  uid: number;
}

export interface SignsData {
  id: string;
  signs: string;
}

export interface SkillData {
  allowMarking: number;
  availableInHouse: number;
  clientDisplay: number;
  cursor: number;
  elementActionId: number;
  gatheredRessourceItem: number;
  id: Generated<number>;
  isForgemagus: number;
  levelMin: number;
  nameId: number;
  parentJobId: number;
  range: number;
  useAnimation: string;
  useRangeInClient: number;
}

export interface SkillDataCraftableItemIdsJunction {
  SkillData_id: number | null;
  target_id: number | null;
}

export interface SkillDataModifiableItemTypeIdsJunction {
  SkillData_id: number | null;
  target_id: number | null;
}

export interface SkillNameData {
  id: Generated<number>;
  nameId: number;
}

export interface SkinMappingData {
  id: Generated<number>;
  lowDefId: number;
}

export interface SkinSlotRuleData {
  id: string;
  skinId: number;
  slotRulesList: string;
}

export interface SmileyData {
  categoryId: number;
  forPlayers: number;
  gfxId: string;
  id: Generated<number>;
  order: number;
  referenceId: number;
}

export interface SmileyPackData {
  id: Generated<number>;
  nameId: number;
  order: number;
  smileys: string;
}

export interface SocialRightData {
  groupId: number;
  id: number;
  nameId: number;
  order: number;
  source: string;
}

export interface SoundBoneData {
  animSounds: string;
  id: string;
}

export interface SpeakingItemTextData {
  id: string;
  textId: number;
  textLevel: number;
  textProba: number;
  textRestriction: string;
  textSound: number;
  textStringId: string;
}

export interface SpeakingItemTriggerData {
  id: string;
}

export interface SpeakingItemTriggerDataTextIdsJunction {
  SpeakingItemTriggerData_id: number | null;
  target_id: number | null;
}

export interface SpellBombData {
  chainReactionSpellId: number;
  comboCoeff: number;
  explodSpellId: number;
  id: Generated<number>;
  instantSpellId: number;
  wallId: number;
}

export interface SpellBombWallData {
  color: number;
  id: Generated<number>;
  linear: number;
  maxHop: number;
  minHop: number;
  spellId: number;
}

export interface SpellData {
  adminName: string;
  basePreviewZoneDescr: string;
  boundScriptUsageData: string;
  criticalHitBoundScriptUsageData: string;
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  m_flags: number;
  nameId: number;
  order: number;
  scriptId: number;
  scriptIdCritical: number;
  scriptParams: string;
  scriptParamsCritical: string;
  spellLevels: string;
  typeId: number;
}

export interface SpellLevelData {
  apCost: number;
  criticalEffect: string;
  criticalHitProbability: number;
  effects: string;
  globalCooldown: number;
  grade: number;
  id: Generated<number>;
  initialCooldown: number;
  m_flags: number;
  maxCastPerTarget: number;
  maxCastPerTurn: number;
  maxGlobalCastPerTarget: number;
  maxGlobalCastPerTurn: number;
  maxStack: number;
  minCastInterval: number;
  minPlayerLevel: number;
  minRange: number;
  previewZones: string;
  range: number;
  spellBreed: number;
  spellId: number;
  statesCriterion: string;
}

export interface SpellPairData {
  descriptionId: number;
  iconId: number;
  id: Generated<number>;
  nameId: number;
}

export interface SpellScriptData {
  id: string;
  rawParams: string;
  type: number;
}

export interface SpellStateData {
  cantBeMoved: number;
  cantBePushed: number;
  cantBeTackled: number;
  cantDealDamage: number;
  cantSwitchPosition: number;
  cantTackle: number;
  displayTurnRemaining: number;
  icon: string;
  iconVisibilityMask: number;
  id: Generated<number>;
  incurable: number;
  invulnerable: number;
  invulnerableMelee: number;
  invulnerableRange: number;
  isMainState: number;
  isSilent: number;
  nameId: number;
  preventsFight: number;
  preventsSpellCast: number;
}

export interface SpellStateDataEffectsIdsJunction {
  SpellStateData_id: number | null;
  target_id: number | null;
}

export interface SpellTypeData {
  id: Generated<number>;
  longNameId: string;
  shortNameId: string;
}

export interface SpellVariantData {
  breedId: number;
  id: Generated<number>;
}

export interface SpellVariantDataSpellIdsJunction {
  SpellVariantData_id: number | null;
  target_id: number | null;
}

export interface StealthBoneData {
  id: Generated<number>;
}

export interface SubAreaData {
  achievements: string;
  areaId: number;
  associatedZaapMapId: number;
  basicAccountAllowed: number;
  bounds: string;
  capturable: number;
  customWorldMapId: number;
  displayOnWorldMap: number;
  dungeonId: number;
  exploreAchievementId: number;
  harvestables: string;
  id: Generated<number>;
  isConquestVillage: number;
  level: number;
  monsters: string;
  mountAutoTripAllowed: number;
  nameId: number;
  neighbors: string;
  packId: number;
  psiAllowed: number;
  shape: string;
}

export interface SubAreaDataEntranceMapIdsJunction {
  SubAreaData_id: number | null;
  target_id: number | null;
}

export interface SubAreaDataExitMapIdsJunction {
  SubAreaData_id: number | null;
  target_id: number | null;
}

export interface SubAreaDataMapIdsJunction {
  SubAreaData_id: number | null;
  target_id: number | null;
}

export interface SuperAreaData {
  hasWorldMap: number;
  id: Generated<number>;
  nameId: number;
  worldmapId: number;
}

export interface TaxCollectorFirstnameData {
  firstnameId: string;
  id: Generated<number>;
}

export interface TaxCollectorNameData {
  id: Generated<number>;
  nameId: number;
}

export interface TextIconReferenceData {
  id: string;
  referenceKey: string;
}

export interface TitleCategoryData {
  id: Generated<number>;
  nameId: number;
}

export interface TitleData {
  categoryId: number;
  id: Generated<number>;
  nameFemaleId: string;
  nameMaleId: string;
  visible: number;
}

export interface Translations {
  id: number;
  lang: string;
  value: string | null;
}

export interface VeteranRewardData {
  id: Generated<number>;
  itemGID: number;
  itemQuantity: number;
  requiredSubDays: number;
}

export interface WaypointData {
  activated: number;
  id: Generated<number>;
  mapId: number;
  subAreaId: number;
}

export interface WeaponData {
  apCost: number;
  appearanceId: number;
  castInDiagonal: number;
  castInLine: number;
  castTestLos: number;
  craftConditionalCriterion: string;
  craftFeasibleCriterion: string;
  craftVisibleCriterion: string;
  craftXpRatio: number;
  criterions: string;
  criterionsTarget: string;
  criticalHitBonus: number;
  criticalHitProbability: number;
  descriptionId: number;
  favoriteRecyclingSubareas: string;
  favoriteSubAreas: string;
  favoriteSubAreasBonus: number;
  iconId: number;
  id: Generated<number>;
  importantNoticeId: string;
  isColorable: number;
  itemSetId: number;
  level: number;
  m_flags: number;
  maxCastPerTurn: number;
  minRange: number;
  nameId: number;
  possibleEffects: string;
  price: number;
  range: number;
  realWeight: number;
  recipeSlots: number;
  recyclingNuggets: number;
  resourcesBySubarea: string;
  typeId: number;
  visibilityCriterion: string;
}

export interface WeaponDataDropMonsterIdsJunction {
  target_id: number | null;
  WeaponData_id: number | null;
}

export interface WeaponDataDropTemporisMonsterIdsJunction {
  target_id: number | null;
  WeaponData_id: number | null;
}

export interface WeaponDataEvolutiveEffectIdsJunction {
  target_id: number | null;
  WeaponData_id: number | null;
}

export interface WeaponDataRecipeIdsJunction {
  target_id: number | null;
  WeaponData_id: number | null;
}

export interface WorldEventData {
  areas: string;
  categoryId: number;
  deletedObjects: string;
  descriptionId: number;
  dungeonHunterGroupsPerMap: number;
  duration: number;
  endMsgId: number;
  fightScenarios: string;
  globalDrops: string;
  id: Generated<number>;
  level: number;
  monsterHunterGroupsPerMap: number;
  nameId: number;
  preMsgDelay: number;
  preMsgId: number;
  startMsgId: number;
  subareas: string;
  worldEventDataType: number;
  worldEventEventId: number;
  worldEventRewardId: number;
}

export interface WorldEventDungeonData {
  dungeonId: number;
  dungeonMapIdTeleport: number;
  id: string;
  scoreGroupShared: number;
  scorePerDamage: number;
  scorePerDungeon: number;
}

export interface WorldEventFarmingSimulatorData {
  id: string;
  scorePerHarvest: number;
}

export interface WorldEventMonstersHunterData {
  areaList: string;
  criterion: string;
  id: string;
  mapList: string;
  monsterList: string;
  scoreGroupShared: number;
  scorePerDamage: number;
  scorePerMonster: number;
  subareaList: string;
}

export interface WorldEventRewardData {
  criterions: string;
  emotes: string;
  experience: number;
  gameaction: number;
  guildPoints: number;
  id: string;
  isForTeam: number;
  kamas: number;
  objects: string;
  order: number;
  ornaments: string;
  rankingConditions: string;
  spells: string;
  titles: string;
  worldEventRewardId: number;
}

export interface WorldEventWorldBossesData {
  areaList: string;
  criterion: string;
  id: string;
  mapList: string;
  monsterList: string;
  scoreDayCount: number;
  scoreGroupShared: number;
  scorePerDamage: number;
  scoreRatio: number;
  scoreTotal: number;
  subareaList: string;
}

export interface WorldMapData {
  id: Generated<number>;
  mapHeight: number;
  mapWidth: number;
  maxScale: number;
  minScale: number;
  nameId: number;
  origineX: number;
  origineY: number;
  startScale: number;
  totalHeight: number;
  totalWidth: number;
  visibleOnMap: number;
  zoom: string;
}

export interface DB {
  AchievementCategoryData: AchievementCategoryData;
  AchievementCategoryData_achievementIds_junction: AchievementCategoryDataAchievementIdsJunction;
  AchievementData: AchievementData;
  AchievementData_objectiveIds_junction: AchievementDataObjectiveIdsJunction;
  AchievementData_rewardIds_junction: AchievementDataRewardIdsJunction;
  AchievementObjectiveData: AchievementObjectiveData;
  AchievementRewardData: AchievementRewardData;
  ActionFilterData: ActionFilterData;
  ActivitySuggestionCategoryData: ActivitySuggestionCategoryData;
  ActivitySuggestionData: ActivitySuggestionData;
  AlignmentGiftData: AlignmentGiftData;
  AlignmentOrderData: AlignmentOrderData;
  AlignmentRankData: AlignmentRankData;
  AlignmentRankGiftsData: AlignmentRankGiftsData;
  AlignmentSideData: AlignmentSideData;
  AlignmentTitleData: AlignmentTitleData;
  AllianceRankData: AllianceRankData;
  AllianceRankNameSuggestionData: AllianceRankNameSuggestionData;
  AllianceRightData: AllianceRightData;
  AllianceRightGroupData: AllianceRightGroupData;
  AllianceTagData: AllianceTagData;
  AllianceTagTypeData: AllianceTagTypeData;
  AlmanaxCalendarData: AlmanaxCalendarData;
  AlmanaxCalendarData_bonusesIds_junction: AlmanaxCalendarDataBonusesIdsJunction;
  AlmanaxCategoryData: AlmanaxCategoryData;
  AlmanaxZodiacData: AlmanaxZodiacData;
  AlterationCategoryData: AlterationCategoryData;
  AlterationData: AlterationData;
  AppearanceData: AppearanceData;
  AreaData: AreaData;
  AreaData_subareaIds_junction: AreaDataSubareaIdsJunction;
  ArenaLeagueData: ArenaLeagueData;
  ArenaLeagueSeasonData: ArenaLeagueSeasonData;
  AuctionHouseData: AuctionHouseData;
  BodyData: BodyData;
  BonusCriterionData: BonusCriterionData;
  BonusData: BonusData;
  BonusData_criterionsIds_junction: BonusDataCriterionsIdsJunction;
  BreachBossData: BreachBossData;
  BreachDungeonModificatorData: BreachDungeonModificatorData;
  BreachPrizeData: BreachPrizeData;
  BreachWorldMapCoordinateData: BreachWorldMapCoordinateData;
  BreachWorldMapSectorData: BreachWorldMapSectorData;
  BreedData: BreedData;
  BreedRoleData: BreedRoleData;
  CalendarEventData: CalendarEventData;
  CardBackgroundData: CardBackgroundData;
  ChallengeData: ChallengeData;
  CharacteristicCategoryData: CharacteristicCategoryData;
  CharacteristicCategoryData_characteristicIds_junction: CharacteristicCategoryDataCharacteristicIdsJunction;
  CharacteristicData: CharacteristicData;
  CharacterXpMappingData: CharacterXpMappingData;
  ChatChannelData: ChatChannelData;
  ChoiceData: ChoiceData;
  CollectableData: CollectableData;
  CollectionData: CollectionData;
  CompanionCharacteristicData: CompanionCharacteristicData;
  CompanionData: CompanionData;
  CompanionSpellData: CompanionSpellData;
  ConstantData: ConstantData;
  CreatureBoneOverrideData: CreatureBoneOverrideData;
  CreatureBoneTypeData: CreatureBoneTypeData;
  CustomModeBreedSpellData: CustomModeBreedSpellData;
  DocumentData: DocumentData;
  DofusProgressionData: DofusProgressionData;
  DungeonData: DungeonData;
  DungeonData_mapIds_junction: DungeonDataMapIdsJunction;
  EffectData: EffectData;
  EffectInstanceDice: EffectInstanceDice;
  EmblemBackgroundData: EmblemBackgroundData;
  EmblemSymbolCategoryData: EmblemSymbolCategoryData;
  EmblemSymbolData: EmblemSymbolData;
  EmoticonData: EmoticonData;
  EvolutiveEffectData: EvolutiveEffectData;
  EvolutiveItemTypeData: EvolutiveItemTypeData;
  ExpeditionSeasonData: ExpeditionSeasonData;
  ExternalNotificationData: ExternalNotificationData;
  FeatureDescriptionData: FeatureDescriptionData;
  FightScenarioData: FightScenarioData;
  ForgettableSpellData: ForgettableSpellData;
  GuildChestTabData: GuildChestTabData;
  GuildHallData: GuildHallData;
  GuildHallThemeData: GuildHallThemeData;
  GuildLevelRewardData: GuildLevelRewardData;
  GuildMissionActivityData: GuildMissionActivityData;
  GuildMissionActivityData_milestonesIds_junction: GuildMissionActivityDataMilestonesIdsJunction;
  GuildMissionData: GuildMissionData;
  GuildMissionGradeData: GuildMissionGradeData;
  GuildMissionMilestoneData: GuildMissionMilestoneData;
  GuildMissionObjectiveData: GuildMissionObjectiveData;
  GuildMissionRankData: GuildMissionRankData;
  GuildMissionSuperCategoryData: GuildMissionSuperCategoryData;
  GuildRaidData: GuildRaidData;
  GuildRaidsGoalData: GuildRaidsGoalData;
  GuildRaidsGroupData: GuildRaidsGroupData;
  GuildRaidsLaddersRewardData: GuildRaidsLaddersRewardData;
  GuildRaidsReward: GuildRaidsReward;
  GuildRankData: GuildRankData;
  GuildRankNameSuggestionData: GuildRankNameSuggestionData;
  GuildRightData: GuildRightData;
  GuildRightGroupData: GuildRightGroupData;
  GuildShopBoostData: GuildShopBoostData;
  GuildTagData: GuildTagData;
  GuildTagTypeData: GuildTagTypeData;
  HavenbagFurnitureData: HavenbagFurnitureData;
  HavenbagThemeData: HavenbagThemeData;
  HeadData: HeadData;
  HintCategoryData: HintCategoryData;
  HintData: HintData;
  HouseData: HouseData;
  IdleData: IdleData;
  InfiniteDreamIntensityData: InfiniteDreamIntensityData;
  InfiniteDreamRewardActionData: InfiniteDreamRewardActionData;
  InfiniteDreamRewardData: InfiniteDreamRewardData;
  InfiniteDreamTrialData: InfiniteDreamTrialData;
  InfoMessageData: InfoMessageData;
  InteractiveData: InteractiveData;
  ItemData: ItemData;
  ItemData_dropMonsterIds_junction: ItemDataDropMonsterIdsJunction;
  ItemData_dropTemporisMonsterIds_junction: ItemDataDropTemporisMonsterIdsJunction;
  ItemData_evolutiveEffectIds_junction: ItemDataEvolutiveEffectIdsJunction;
  ItemData_recipeIds_junction: ItemDataRecipeIdsJunction;
  ItemSetData: ItemSetData;
  ItemSuperTypeData: ItemSuperTypeData;
  ItemTypeData: ItemTypeData;
  JobData: JobData;
  KothRoleData: KothRoleData;
  LegendaryPowerCategoryData: LegendaryPowerCategoryData;
  LegendaryTreasureHuntData: LegendaryTreasureHuntData;
  LivingObjectSkinMoodsData: LivingObjectSkinMoodsData;
  LobbyTagData: LobbyTagData;
  LobbyTypeData: LobbyTypeData;
  LuaFormulaData: LuaFormulaData;
  MapInformationData: MapInformationData;
  MapReferenceData: MapReferenceData;
  MapsCoordinateData: MapsCoordinateData;
  MapsCoordinateData_mapIds_junction: MapsCoordinateDataMapIdsJunction;
  MapScrollActionData: MapScrollActionData;
  ModsterData: ModsterData;
  MonsterData: MonsterData;
  MonsterMiniBossData: MonsterMiniBossData;
  MonsterRaceData: MonsterRaceData;
  MonsterSuperRaceData: MonsterSuperRaceData;
  MonthData: MonthData;
  MountBehaviorData: MountBehaviorData;
  MountBoneData: MountBoneData;
  MountData: MountData;
  MountFamilyData: MountFamilyData;
  NamingRuleData: NamingRuleData;
  NotificationData: NotificationData;
  NpcActionData: NpcActionData;
  NpcData: NpcData;
  NpcDialogSkinData: NpcDialogSkinData;
  NpcMessageData: NpcMessageData;
  OptionalFeatureData: OptionalFeatureData;
  OrnamentData: OrnamentData;
  PaddockGaugesData: PaddockGaugesData;
  PaddocksData: PaddocksData;
  PointOfInterestData: PointOfInterestData;
  PopupInformationData: PopupInformationData;
  PresetIconData: PresetIconData;
  ProgressingAchievementSeasonData: ProgressingAchievementSeasonData;
  ProgressingAchievementStepData: ProgressingAchievementStepData;
  QuestCategoryData: QuestCategoryData;
  QuestCategoryData_questIds_junction: QuestCategoryDataQuestIdsJunction;
  QuestData: QuestData;
  QuestData_stepIds_junction: QuestDataStepIdsJunction;
  QuestObjectiveBringItemToNpcData: QuestObjectiveBringItemToNpcData;
  QuestObjectiveBringSoulToNpcData: QuestObjectiveBringSoulToNpcData;
  QuestObjectiveCraftItemData: QuestObjectiveCraftItemData;
  QuestObjectiveDiscoverMapData: QuestObjectiveDiscoverMapData;
  QuestObjectiveDiscoverSubAreaData: QuestObjectiveDiscoverSubAreaData;
  QuestObjectiveFightMonsterData: QuestObjectiveFightMonsterData;
  QuestObjectiveFightMonstersOnMapData: QuestObjectiveFightMonstersOnMapData;
  QuestObjectiveFreeFormData: QuestObjectiveFreeFormData;
  QuestObjectiveGoToNpcData: QuestObjectiveGoToNpcData;
  QuestObjectiveMultiFightMonsterData: QuestObjectiveMultiFightMonsterData;
  QuestObjectiveTypeData: QuestObjectiveTypeData;
  QuestStepData: QuestStepData;
  QuestStepData_objectiveIds_junction: QuestStepDataObjectiveIdsJunction;
  QuestStepData_rewardsIds_junction: QuestStepDataRewardsIdsJunction;
  QuestStepRewardData: QuestStepRewardData;
  RandomDropGroupData: RandomDropGroupData;
  RecipeData: RecipeData;
  RecipeData_ingredientIds_junction: RecipeDataIngredientIdsJunction;
  RideFoodData: RideFoodData;
  RideGaugesData: RideGaugesData;
  RiderBoneData: RiderBoneData;
  RidesData: RidesData;
  RideSpeciesData: RideSpeciesData;
  ServerCommunityData: ServerCommunityData;
  ServerCommunityData_supportedLangIds_junction: ServerCommunityDataSupportedLangIdsJunction;
  ServerData: ServerData;
  ServerGameTypeData: ServerGameTypeData;
  ServerLangData: ServerLangData;
  ServerPopulationData: ServerPopulationData;
  ServerSeasonData: ServerSeasonData;
  SignsData: SignsData;
  SkillData: SkillData;
  SkillData_craftableItemIds_junction: SkillDataCraftableItemIdsJunction;
  SkillData_modifiableItemTypeIds_junction: SkillDataModifiableItemTypeIdsJunction;
  SkillNameData: SkillNameData;
  SkinMappingData: SkinMappingData;
  SkinSlotRuleData: SkinSlotRuleData;
  SmileyData: SmileyData;
  SmileyPackData: SmileyPackData;
  SocialRightData: SocialRightData;
  SoundBoneData: SoundBoneData;
  SpeakingItemTextData: SpeakingItemTextData;
  SpeakingItemTriggerData: SpeakingItemTriggerData;
  SpeakingItemTriggerData_textIds_junction: SpeakingItemTriggerDataTextIdsJunction;
  SpellBombData: SpellBombData;
  SpellBombWallData: SpellBombWallData;
  SpellData: SpellData;
  SpellLevelData: SpellLevelData;
  SpellPairData: SpellPairData;
  SpellScriptData: SpellScriptData;
  SpellStateData: SpellStateData;
  SpellStateData_effectsIds_junction: SpellStateDataEffectsIdsJunction;
  SpellTypeData: SpellTypeData;
  SpellVariantData: SpellVariantData;
  SpellVariantData_spellIds_junction: SpellVariantDataSpellIdsJunction;
  StealthBoneData: StealthBoneData;
  SubAreaData: SubAreaData;
  SubAreaData_entranceMapIds_junction: SubAreaDataEntranceMapIdsJunction;
  SubAreaData_exitMapIds_junction: SubAreaDataExitMapIdsJunction;
  SubAreaData_mapIds_junction: SubAreaDataMapIdsJunction;
  SuperAreaData: SuperAreaData;
  TaxCollectorFirstnameData: TaxCollectorFirstnameData;
  TaxCollectorNameData: TaxCollectorNameData;
  TextIconReferenceData: TextIconReferenceData;
  TitleCategoryData: TitleCategoryData;
  TitleData: TitleData;
  translations: Translations;
  VeteranRewardData: VeteranRewardData;
  WaypointData: WaypointData;
  WeaponData: WeaponData;
  WeaponData_dropMonsterIds_junction: WeaponDataDropMonsterIdsJunction;
  WeaponData_dropTemporisMonsterIds_junction: WeaponDataDropTemporisMonsterIdsJunction;
  WeaponData_evolutiveEffectIds_junction: WeaponDataEvolutiveEffectIdsJunction;
  WeaponData_recipeIds_junction: WeaponDataRecipeIdsJunction;
  WorldEventData: WorldEventData;
  WorldEventDungeonData: WorldEventDungeonData;
  WorldEventFarmingSimulatorData: WorldEventFarmingSimulatorData;
  WorldEventMonstersHunterData: WorldEventMonstersHunterData;
  WorldEventRewardData: WorldEventRewardData;
  WorldEventWorldBossesData: WorldEventWorldBossesData;
  WorldMapData: WorldMapData;
}
