/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface AbuseReasons {
  abuseReasonId: number;
  id: string;
  mask: number;
  reasonTextId: number;
}

export interface AchievementCategories {
  color: string;
  icon: string;
  id: number;
  nameId: number;
  order: number;
  parentId: number | null;
  visibilityCriterion: string | null;
}

export interface AchievementCategoriesAchievementIdsJunction {
  AchievementCategories_id: number | null;
  target_id: number | null;
}

export interface AchievementObjectives {
  achievementId: number;
  criterion: string;
  id: number;
  nameId: number;
  order: number | null;
}

export interface AchievementProgress {
  id: number;
  name: string;
  seasonId: number;
}

export interface AchievementProgressSteps {
  achievementId: number;
  id: number;
  isBuyable: number | null;
  isCosmetic: number;
  progressId: number;
  score: number;
}

export interface AchievementRewards {
  achievementId: number;
  criteria: string;
  emotesReward: string;
  experienceRatio: number | null;
  guildPoints: number | null;
  id: number;
  itemsQuantityReward: string;
  itemsReward: string;
  kamasRatio: number | null;
  kamasScaleWithPlayerLevel: number | null;
  ornamentsReward: string;
  spellsReward: string;
  titlesReward: string;
}

export interface Achievements {
  accountLinked: number | null;
  categoryId: number;
  descriptionId: number;
  iconId: number;
  id: number;
  level: number;
  nameId: number;
  order: number | null;
  points: number;
}

export interface AchievementsObjectiveIdsJunction {
  Achievements_id: number | null;
  target_id: number | null;
}

export interface AchievementsRewardIdsJunction {
  Achievements_id: number | null;
  target_id: number | null;
}

export interface ActionFilters {
  id: number;
  nameId: number;
  order: number;
}

export interface ActivitySuggestions {
  categoryId: number;
  descriptionId: number;
  endDate: number | null;
  icon: string;
  id: number;
  isLarge: number | null;
  level: number;
  mapId: number;
  nameId: number;
  startDate: number | null;
}

export interface ActivitySuggestionsCategories {
  id: number;
  nameId: number;
  parentId: number | null;
}

export interface AlignmentGift {
  id: number;
  nameId: number;
}

export interface AlignmentOrder {
  id: number;
  nameId: number;
  sideId: number | null;
}

export interface AlignmentRank {
  descriptionId: number;
  id: number;
  minimumAlignment: number | null;
  nameId: number;
  orderId: number | null;
}

export interface AlignmentRankJntGift {
  gifts: string;
  id: number;
  levels: string;
}

export interface AlignmentSides {
  id: number;
  nameId: number;
}

export interface AlignmentTitles {
  id: string;
  namesId: string;
  shortsId: string;
  sideId: number | null;
}

export interface AllianceRankNameSuggestions {
  id: string;
  uiKey: string;
}

export interface AllianceRanks {
  gfxId: number;
  id: number;
  isModifiable: number | null;
  nameId: number;
  order: number | null;
}

export interface AllianceRightGroups {
  id: number;
  nameId: number;
  order: number | null;
  rights: string;
}

export interface AllianceRights {
  groupId: number;
  id: number;
  nameId: number;
  order: number | null;
}

export interface AllianceTags {
  id: number;
  nameId: number;
  order: number | null;
  typeId: number;
}

export interface AllianceTagsTypes {
  id: number;
  nameId: number;
}

export interface AlmanaxCalendars {
  descId: string;
  id: number;
  nameId: number;
  npcId: number;
}

export interface AlmanaxCalendarsBonusesIdsJunction {
  AlmanaxCalendars_id: number | null;
  target_id: number | null;
}

export interface AlterationCategories {
  id: number;
  nameId: number;
  parentId: number | null;
}

export interface Alterations {
  categoryId: number;
  criteria: string | null;
  descriptionId: number;
  iconId: number | null;
  id: number;
  isVisible: number | null;
  isWebDisplay: number;
  nameId: number;
  possibleEffects: string;
}

export interface Appearances {
  data: string;
  id: number;
  type: number;
}

export interface Areas {
  bounds: string;
  containHouses: number;
  containPaddocks: number;
  hasSuggestion: number;
  hasWorldMap: number | null;
  id: number;
  nameId: number;
  superAreaId: number | null;
  worldmapId: number | null;
}

export interface ArenaLeagueRewards {
  endSeasonRewards: number;
  id: number;
  leagueId: number;
  seasonId: number;
  titlesRewards: string;
}

export interface ArenaLeagues {
  highRatingBound: number;
  icon: string;
  id: number;
  illus: string;
  isLastLeague: number | null;
  lowRatingBound: number | null;
  nameId: number;
  ornamentId: number;
}

export interface ArenaLeagueSeasons {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number | null;
  uid: number;
}

export interface Bonuses {
  amount: number;
  id: number;
  type: number;
}

export interface BonusesAreaCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BonusesCriterions {
  id: number;
  type: number;
  value: number;
}

export interface BonusesCriterionsIdsJunction {
  Bonuses_id: number | null;
  target_id: number | null;
}

export interface BonusesEquippedItemCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BonusesMonsterCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BonusesMonsterFamilyCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BonusesQuestCategoryCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BonusesSubAreaCriterion {
  id: number;
  type: number;
  value: number;
}

export interface BreachBosses {
  accessCriterion: string;
  apparitionCriterion: string;
  category: number;
  id: number;
  incompatibleBosses: string;
  monsterId: number;
  rewardId: number;
}

export interface BreachDungeonModificators {
  additionalRewardPercent: number;
  criterion: string | null;
  id: number;
  isPositiveForPlayers: number | null;
  modificatorId: number;
  score: number;
  tooltipBaseline: string;
}

export interface BreachInfinityLevels {
  id: number;
  level: number | null;
  nameId: number;
}

export interface BreachPrizes {
  categoryId: number;
  currency: number | null;
  descriptionKey: string | null;
  id: number;
  itemId: number;
  nameId: number;
  tooltipKey: string;
}

export interface BreachWorldMapCoordinates {
  exploredMapIcon: number;
  id: number;
  mapCoordinateX: number;
  mapCoordinateY: number;
  mapStage: number;
  unexploredMapIcon: number;
}

export interface BreachWorldMapSectors {
  id: number;
  legendId: string;
  maxStage: number;
  minStage: number;
  sectorIcon: string;
  sectorNameId: string;
}

export interface BreedRoles {
  assetId: number;
  color: number;
  descriptionId: number;
  id: number;
  nameId: number;
}

export interface Breeds {
  breedRoles: string;
  breedSpellsId: string;
  complexity: number;
  creatureBonesId: number;
  descriptionId: number;
  femaleArtwork: number;
  femaleColors: string;
  femaleLook: string;
  gameplayClassDescriptionId: string;
  gameplayDescriptionId: string;
  guideItemId: number;
  id: number;
  longNameId: string;
  maleArtwork: number;
  maleColors: string;
  maleLook: string;
  shortNameId: string;
  sortIndex: number;
  spawnMap: number;
  statsPointsForAgility: string;
  statsPointsForChance: string;
  statsPointsForIntelligence: string;
  statsPointsForStrength: string;
  statsPointsForVitality: string;
  statsPointsForWisdom: string;
}

export interface CensoredContents {
  id: string;
  lang: string;
  newValue: number;
  oldValue: number;
  type: number;
}

export interface CensoredWords {
  deepLooking: number | null;
  id: number;
  language: string;
  listId: number | null;
  word: string;
}

export interface Challenges {
  activationCriterion: string;
  categoryId: number;
  completionCriterion: string;
  descriptionId: number;
  iconId: number;
  id: number;
  incompatibleChallenges: string;
  nameId: number;
  targetMonsterId: number | null;
}

export interface CharacteristicCategories {
  id: number;
  nameId: number;
  order: number;
}

export interface CharacteristicCategoriesCharacteristicIdsJunction {
  CharacteristicCategories_id: number | null;
  target_id: number | null;
}

export interface Characteristics {
  asset: string;
  categoryId: number;
  id: number;
  keyword: string;
  nameId: number;
  order: number;
  scaleFormulaId: number;
  upgradable: number | null;
  visible: number;
}

export interface CharacterXPMappings {
  experiencePoints: number | null;
  id: string;
  level: number;
}

export interface ChatChannels {
  allowObjects: number | null;
  descriptionId: number;
  id: number;
  isPrivate: number | null;
  nameId: number;
  shortcut: string;
  shortcutKey: string;
}

export interface Choices {
  choiceNameId: number;
  duration: number;
  id: number;
  options: string;
  proposalCount: number;
}

export interface Collectables {
  entityId: number;
  gfxId: number | null;
  id: string;
  name: string;
  order: number;
  rarity: number;
  typeId: number;
}

export interface Collections {
  collectables: string;
  criterion: string;
  id: string;
  name: string;
  typeId: number;
}

export interface CompanionCharacteristics {
  caracId: number | null;
  companionId: number;
  id: number;
  order: number | null;
  statPerLevelRange: string;
}

export interface Companions {
  assetId: number;
  characteristics: string;
  creatureBoneId: number;
  descriptionId: number;
  id: number;
  look: string;
  nameId: number;
  spells: string;
  startingSpellLevelId: number;
  visibility: string | null;
  webDisplay: number;
}

export interface CompanionSpells {
  companionId: number;
  gradeByLevel: string;
  id: number;
  spellId: number;
}

export interface CreatureBonesOverrides {
  boneId: number;
  creatureBoneId: number;
  id: string;
}

export interface CreatureBonesTypes {
  creatureBoneId: number;
  id: number;
}

export interface CustomModeBreedSpells {
  breedId: number;
  id: number;
  isHidden: number | null;
  isInitialSpell: number;
  pairId: number;
}

export interface Documents {
  authorId: string;
  clientProperties: string | null;
  contentCSS: string;
  contentId: string;
  id: number;
  showBackgroundImage: number;
  showTitle: number;
  subTitleId: string;
  titleId: string;
  typeId: number;
}

export interface Dungeons {
  entranceMapId: number;
  exitMapId: number;
  id: number;
  nameId: number;
  optimalPlayerLevel: number;
}

export interface DungeonsMapIdsJunction {
  Dungeons_id: number | null;
  target_id: number | null;
}

export interface EffectInstanceDice {
  baseEffectId: number;
  delay: number | null;
  diceNum: number;
  diceSide: number | null;
  dispellable: number;
  displayZero: number | null;
  duration: number | null;
  effectElement: number;
  effectId: number;
  effectTriggerDuration: number | null;
  effectUid: number | null;
  group: number | null;
  id: string;
  m_flags: number;
  modificator: number | null;
  order: number | null;
  random: number | null;
  spellId: number;
  targetId: number | null;
  targetMask: string | null;
  triggers: string | null;
  value: number | null;
  zoneDescr: string;
}

export interface Effects {
  actionFiltersId: string;
  active: number | null;
  bonusType: number | null;
  boost: number | null;
  category: number | null;
  characteristic: number | null;
  characteristicOperator: string | null;
  descriptionId: number;
  effectPowerRate: number | null;
  effectPriority: number | null;
  effectTriggerDuration: number | null;
  elementId: number;
  forceMinMax: number | null;
  hideValueInTooltip: number;
  iconId: number | null;
  id: number;
  isInPercent: number | null;
  oppositeId: number | null;
  showInSet: number | null;
  showInTooltip: number | null;
  textIconReferenceId: number | null;
  theoreticalDescriptionId: string;
  theoreticalPattern: number;
  useDice: number | null;
  useInFight: number | null;
}

export interface EmblemBackgrounds {
  id: number;
  order: number;
}

export interface EmblemSymbolCategories {
  id: number;
  nameId: number;
}

export interface EmblemSymbols {
  categoryId: number;
  colorizable: number;
  iconId: number;
  id: number;
  order: number;
  skinId: number;
}

export interface Emoticons {
  animName: string;
  aura: number | null;
  cooldown: number;
  duration: number | null;
  eightDirections: number | null;
  id: number;
  nameId: number;
  order: number;
  persistancy: number | null;
  scale: number;
  shortcutId: string;
  spellLevelId: number | null;
  weight: number | null;
}

export interface EvolutiveEffects {
  actionId: number;
  id: number;
  progressionPerLevelRange: string;
  targetId: number;
}

export interface EvolutiveItemTypes {
  experienceBoost: number;
  experienceByLevel: string;
  id: number;
  maxLevel: number;
}

export interface ExpeditionSeasons {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number;
  uid: number;
}

export interface ExternalNotifications {
  categoryId: number;
  colorId: number;
  defaultEnable: number;
  defaultMultiAccount: number;
  defaultNotify: number | null;
  defaultSound: number;
  descriptionId: number;
  iconId: number;
  id: number;
  messageId: string;
  name: string;
}

export interface FeatureDescriptions {
  children: string;
  criterion: string | null;
  descriptionId: number;
  id: number;
  images: string;
  nameId: number;
  parentId: number | null;
  priority: number;
}

export interface FightScenarios {
  id: number;
  nameId: string;
}

export interface FinishMoves {
  category: number;
  duration: number;
  free: number;
  id: number;
  nameId: number;
  spellLevel: number;
}

export interface ForgettableSpells {
  id: number;
  itemId: number;
  pairId: number;
}

export interface GuildChestTabs {
  cost: number | null;
  dropRight: number;
  gfxId: number;
  id: string;
  index: number;
  nameId: number;
  openRight: number;
  seniority: number | null;
  serverType: number;
  tabId: number;
  takeRight: number;
}

export interface GuildRankNameSuggestions {
  id: string;
  uiKey: string;
}

export interface GuildRanks {
  gfxId: number;
  id: number;
  nameId: number;
  order: number | null;
}

export interface GuildRightGroups {
  id: number;
  nameId: number;
  order: number | null;
  rights: string;
}

export interface GuildRights {
  groupId: number;
  id: number;
  nameId: number;
  order: number | null;
}

export interface GuildTags {
  id: number;
  nameId: number;
  order: number;
  typeId: number;
}

export interface GuildTagsTypes {
  id: number;
  nameId: number;
}

export interface HavenbagFurnitures {
  blocksMovement: number;
  cellsHeight: number;
  cellsWidth: number;
  color: number;
  elementId: number;
  gfxId: number;
  height: number;
  horizontalSymmetry: number | null;
  id: string;
  isStackable: number;
  layerId: number;
  order: number | null;
  origin: string;
  size: string;
  skillId: number | null;
  themeId: number;
  typeId: number;
}

export interface HavenbagThemes {
  id: number;
  mapId: number;
  nameId: number;
}

export interface Heads {
  assetId: string;
  breed: number;
  gender: number | null;
  id: number;
  label: string;
  order: number | null;
  payable: number | null;
  skins: string;
}

export interface HintCategory {
  id: number;
  nameId: number;
}

export interface Hints {
  categoryId: number;
  gfx: number;
  id: number;
  level: number | null;
  mapId: number;
  nameId: number;
  outdoor: number | null;
  realMapId: number | null;
  subareaId: number;
  worldMapId: number;
  x: number;
  y: number;
}

export interface Houses {
  defaultPrice: number;
  descriptionId: number | null;
  gfxId: number;
  id: string;
  nameId: number;
  roomCount: number;
  typeId: number;
}

export interface IncarnationLevels {
  id: number;
  incarnationId: number;
  level: number;
  requiredXp: number | null;
}

export interface InfoMessages {
  id: string;
  messageId: number | null;
  textId: number;
  typeId: number | null;
}

export interface Interactives {
  actionId: number;
  displayTooltip: number;
  id: number;
  nameId: number;
}

export interface Items {
  appearanceId: number | null;
  changeVersion: string | null;
  craftConditional: string | null;
  craftFeasible: string;
  craftVisible: string;
  craftXpRatio: number;
  criteria: string | null;
  criteriaTarget: string | null;
  descriptionId: number;
  favoriteRecyclingSubareas: string;
  favoriteSubAreas: string;
  favoriteSubAreasBonus: number | null;
  iconId: number;
  id: number;
  importantNoticeId: string | null;
  isColorable: number | null;
  itemSetId: number;
  level: number;
  m_flags: number;
  nameId: number;
  possibleEffects: string;
  price: number;
  realWeight: number;
  recipeSlots: number;
  recyclingNuggets: number | null;
  resourcesBySubarea: string;
  tooltipExpirationDate: string;
  typeId: number;
  useAnimationId: number;
  visibility: string | null;
}

export interface ItemsDropMonsterIdsJunction {
  Items_id: number | null;
  target_id: number | null;
}

export interface ItemsDropTemporisMonsterIdsJunction {
  Items_id: number | null;
  target_id: number | null;
}

export interface ItemSets {
  bonusIsSecret: number | null;
  effects: string;
  id: number;
  items: string;
  nameId: number;
}

export interface ItemsEvolutiveEffectIdsJunction {
  Items_id: number | null;
  target_id: number | null;
}

export interface ItemsRecipeIdsJunction {
  Items_id: number | null;
  target_id: number | null;
}

export interface ItemSuperTypes {
  id: number;
  possiblePositions: string;
}

export interface ItemTypes {
  categoryId: number | null;
  craftXpRatio: number;
  evolutiveTypeId: number | null;
  gender: number;
  id: number;
  isInEncyclopedia: number;
  mimickable: number;
  nameId: number;
  plural: number | null;
  possiblePositions: string;
  rawZone: string | null;
  superTypeId: number;
}

export interface Jobs {
  hasLegendaryCraft: number | null;
  iconId: number;
  id: number;
  nameId: number;
}

export interface KothRoles {
  id: number;
  isDefault: number | null;
  nameId: number;
}

export interface LegendaryPowersCategories {
  categoryName: string;
  categoryOverridable: number;
  categorySpells: string;
  id: number;
}

export interface LegendaryTreasureHunts {
  chestId: number;
  id: number;
  level: number;
  mapItemId: number;
  monsterId: number;
  nameId: number;
  xpRatio: number;
}

export interface LivingObjectSkinJntMood {
  id: string;
  moods: string;
  skinId: number;
}

export interface LuaFormulas {
  formulaName: string;
  id: number;
  luaFormula: string;
}

export interface MapCoordinates {
  compressedCoords: number;
  id: string;
}

export interface MapCoordinatesMapIdsJunction {
  MapCoordinates_id: number | null;
  target_id: number | null;
}

export interface MapPositions {
  fightSnapshot: string;
  id: number;
  m_flags: number;
  nameId: number | null;
  playlistIds: string;
  posX: number | null;
  posY: number | null;
  roleplaySnapshot: string;
  subAreaId: number;
  tacticalModeTemplateId: number | null;
  worldMap: number;
}

export interface MapReferences {
  cellId: number;
  id: number;
  mapId: number;
}

export interface MapScrollActions {
  bottomExists: number;
  bottomMapId: number;
  id: number;
  leftExists: number;
  leftMapId: number;
  rightExists: number;
  rightMapId: number;
  topExists: number;
  topMapId: number;
}

export interface Modsters {
  id: number;
  itemId: number;
  modsterAchievements: string;
  modsterActiveSpells: string;
  modsterHiddenAchievements: string;
  modsterId: number;
  modsterPassiveSpells: string;
  order: number | null;
  parentsModsterId: string;
}

export interface MonsterDropChanceBonus {
  amount: number;
  id: number;
  type: number;
}

export interface MonsterDropChanceBonusCriterionsIdsJunction {
  MonsterDropChanceBonus_id: number | null;
  target_id: number | null;
}

export interface MonsterMiniBoss {
  id: number;
  monsterReplacingId: number;
}

export interface MonsterRaces {
  aggressiveAttackDelay: number | null;
  aggressiveImmunityCriterion: string | null;
  aggressiveLevelDiff: number | null;
  aggressiveZoneSize: number | null;
  id: number;
  monsters: string;
  nameId: number;
  superRaceId: number;
}

export interface Monsters {
  aggressiveAttackDelay: number;
  aggressiveImmunityCriterion: string;
  aggressiveLevelDiff: number;
  aggressiveZoneSize: number;
  animFunList: string;
  characRatios: string;
  correspondingMiniBossId: number;
  creatureBoneId: number | null;
  drops: string;
  favoriteSubareaId: number;
  gfxId: number;
  grades: string;
  id: number;
  incompatibleChallenges: string;
  incompatibleIdols: string;
  look: string;
  m_flags: number;
  nameId: number;
  race: number;
  scaleGradeRef: number;
  speedAdjust: number;
  spellGrades: string;
  spells: string;
  subareas: string;
  temporisDrops: string;
}

export interface MonsterSuperRaces {
  id: number;
  nameId: number;
}

export interface MonsterXPBonus {
  amount: number;
  id: number;
  type: number;
}

export interface MonsterXPBonusCriterionsIdsJunction {
  MonsterXPBonus_id: number | null;
  target_id: number | null;
}

export interface Months {
  id: number;
  nameId: number;
}

export interface MountBehaviors {
  descriptionId: number;
  id: number;
  nameId: number;
}

export interface MountBones {
  id: number;
}

export interface MountFamily {
  headUri: string;
  id: number;
  nameId: number;
}

export interface Mounts {
  certificateId: number;
  effects: string;
  familyId: number;
  id: number;
  look: string;
  nameId: number;
}

export interface NamingRules {
  id: number;
  maxLength: number;
  minLength: number;
  regexp: string;
}

export interface Notifications {
  cantBeClosed: number | null;
  iconId: number | null;
  id: number;
  messageId: string;
  titleId: string;
  trigger: string | null;
  typeId: number;
}

export interface NpcActions {
  id: number;
  nameId: number;
  realId: number;
}

export interface NpcMessages {
  id: number;
  messageId: string;
  messageParams: string;
}

export interface Npcs {
  actions: string;
  animFunList: string;
  dialogMessages: string;
  dialogReplies: string;
  fastAnimsFun: number | null;
  gender: number | null;
  id: number;
  look: string;
  nameId: number;
  tooltipVisible: number;
}

export interface OptionalFeatures {
  activationCriterions: string | null;
  id: number;
  isActivationOnLaunch: number | null;
  isActivationOnServerConnection: number | null;
  isClient: number;
  isServer: number | null;
  keyword: string;
}

export interface Ornaments {
  assetId: number;
  iconId: number | null;
  id: number;
  nameId: number;
  order: number;
  visible: number;
}

export interface Pack {
  hasSubAreas: number;
  id: number;
  name: string;
}

export interface Playlists {
  crossfadeDuration: number;
  id: number;
  random: number | null;
  sounds: string;
  startRandom: number | null;
  startRandomOnce: number | null;
  type: number;
}

export interface PointOfInterest {
  categoryId: number;
  id: number;
  nameId: number;
}

export interface PointOfInterestCategory {
  id: number;
}

export interface PopupInformations {
  autoTrigger: number;
  buttons: string;
  cacheType: number;
  criterion: string;
  descriptionId: number;
  id: number;
  illuName: string;
  parentId: number;
  titleId: string;
}

export interface PresetIcons {
  id: number;
  order: number | null;
}

export interface QuestCategory {
  id: number;
  nameId: number;
  order: number;
}

export interface QuestCategoryQuestIdsJunction {
  QuestCategory_id: number | null;
  target_id: number | null;
}

export interface QuestKamasBonus {
  amount: number;
  id: number;
  type: number;
}

export interface QuestKamasBonusCriterionsIdsJunction {
  QuestKamasBonus_id: number | null;
  target_id: number | null;
}

export interface QuestObjectiveBringItemToNpc {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveBringSoulToNpc {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveCraftItem {
  coords: string;
  dialogId: number;
  id: number;
  mapId: number | null;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveDiscoverMap {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveDiscoverSubArea {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFightMonster {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFightMonstersOnMap {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveFreeForm {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveGoToNpc {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveMultiFightMonster {
  coords: string;
  dialogId: number | null;
  id: number;
  mapId: number | null;
  parameters: string;
  stepId: number;
  typeId: number;
}

export interface QuestObjectiveTypes {
  id: number;
  nameId: number;
}

export interface Quests {
  categoryId: number;
  followable: number;
  id: number;
  isDungeonQuest: number | null;
  isEvent: number | null;
  isPartyQuest: number | null;
  levelMax: number;
  levelMin: number;
  nameId: number;
  repeatLimit: number;
  repeatType: number;
  startCriterion: string;
}

export interface QuestsStepIdsJunction {
  Quests_id: number | null;
  target_id: number | null;
}

export interface QuestStepRewards {
  emotesReward: string;
  experienceRatio: number;
  id: number;
  itemsReward: string;
  jobsReward: string;
  kamasRatio: number;
  kamasScaleWithPlayerLevel: number | null;
  levelMax: number;
  levelMin: number;
  spellsReward: string;
  stepId: number;
  titlesReward: string;
}

export interface QuestSteps {
  descriptionId: number;
  dialogId: number;
  duration: number;
  id: number;
  nameId: number;
  optimalLevel: number;
  questId: number;
}

export interface QuestStepsObjectiveIdsJunction {
  QuestSteps_id: number | null;
  target_id: number | null;
}

export interface QuestStepsRewardsIdsJunction {
  QuestSteps_id: number | null;
  target_id: number | null;
}

export interface QuestXPBonus {
  amount: number;
  id: number;
  type: number;
}

export interface QuestXPBonusCriterionsIdsJunction {
  QuestXPBonus_id: number | null;
  target_id: number | null;
}

export interface RandomDropGroups {
  description: string;
  displayChances: number;
  displayContent: number;
  id: number;
  name: string;
  randomDropItems: string;
}

export interface Recipes {
  changeVersion: string | null;
  id: string;
  jobId: number;
  quantities: string;
  resultId: number;
  resultLevel: number;
  resultNameId: string;
  resultTypeId: number;
  skillId: number;
  tooltipExpirationDate: string;
}

export interface RecipesIngredientIdsJunction {
  Recipes_id: number | null;
  target_id: number | null;
}

export interface RideFood {
  familyId: number;
  gid: number;
  id: string;
  typeId: number | null;
}

export interface ServerCommunities {
  defaultCountries: string;
  id: number;
  nameId: number;
  namingRuleAdminId: number;
  namingRuleAllianceNameId: number;
  namingRuleAllianceTagId: number;
  namingRuleGuildNameId: number;
  namingRuleModoId: number;
  namingRuleMountNameId: number;
  namingRuleNameGeneratorId: number;
  namingRulePartyNameId: number;
  namingRulePlayerNameId: number;
  namingRulePresetNameId: number;
  shortId: string;
}

export interface ServerCommunitiesSupportedLangIdsJunction {
  ServerCommunities_id: number | null;
  target_id: number | null;
}

export interface ServerGameTypes {
  descriptionId: number;
  id: number;
  nameId: number;
  rulesId: string;
  selectableByPlayer: number;
}

export interface ServerLangs {
  id: number;
  langCode: string;
  nameId: number;
}

export interface ServerPopulations {
  id: number;
  nameId: number;
  weight: number;
}

export interface Servers {
  commentId: string;
  communityId: number;
  gameTypeId: number;
  id: number;
  illus: string;
  language: string;
  monoAccount: number | null;
  nameId: number;
  openingDate: number;
  populationId: number | null;
  restrictedToLanguages: string;
}

export interface ServerSeasons {
  beginning: number;
  closure: number;
  flagObjectId: number;
  id: string;
  nameId: string;
  resetDate: number;
  uid: number;
}

export interface Signs {
  id: number;
  paramsString: string;
  skillId: number;
  textKey: string | null;
}

export interface SkillNames {
  id: number;
  nameId: number;
}

export interface Skills {
  availableInHouse: number | null;
  clientDisplay: number;
  cursor: number;
  elementActionId: number;
  gatheredRessourceItem: number;
  id: number;
  interactiveId: number;
  isForgemagus: number | null;
  levelMin: number;
  nameId: number;
  parentJobId: number;
  range: number;
  useAnimation: string;
  useRangeInClient: number | null;
}

export interface SkillsCraftableItemIdsJunction {
  Skills_id: number | null;
  target_id: number | null;
}

export interface SkillsModifiableItemTypeIdsJunction {
  Skills_id: number | null;
  target_id: number | null;
}

export interface SkinMappings {
  id: number;
  lowDefId: number;
}

export interface SkinSlotsRules {
  id: string;
  skinId: number | null;
  slotRulesList: string;
}

export interface SmileyCategories {
  gfxId: string;
  id: number;
  isFake: number;
  order: number;
}

export interface SmileyPacks {
  id: number;
  nameId: number;
  order: number;
  smileys: string;
}

export interface Smileys {
  categoryId: number;
  forPlayers: number;
  gfxId: string;
  id: number;
  order: number;
  referenceId: number | null;
  triggers: string;
}

export interface SocialRights {
  groupId: number;
  id: number;
  nameId: number;
  order: number | null;
}

export interface SoundBones {
  animSounds: string;
  id: string;
}

export interface SoundUi {
  closeFile: string | null;
  id: number;
  openFile: string | null;
  uiName: string;
}

export interface SoundUiHook {
  id: number;
  name: string;
}

export interface SpeakingItemsText {
  id: string;
  textId: number;
  textLevel: number;
  textProba: number;
  textRestriction: string | null;
  textSound: number;
  textStringId: string;
}

export interface SpeakingItemsTriggers {
  id: string;
  states: string;
  triggersId: number;
}

export interface SpeakingItemsTriggersTextIdsJunction {
  SpeakingItemsTriggers_id: number | null;
  target_id: number | null;
}

export interface SpellBombs {
  chainReactionSpellId: number;
  comboCoeff: number;
  explodSpellId: number;
  id: number;
  instantSpellId: number;
  wallId: number;
}

export interface SpellConversions {
  id: string;
  newSpellId: number;
  oldSpellId: number;
}

export interface SpellLevels {
  apCost: number;
  criticalEffect: string;
  criticalHitProbability: number;
  effects: string;
  globalCooldown: number | null;
  grade: number;
  id: number;
  initialCooldown: number | null;
  m_flags: number;
  maxCastPerTarget: number;
  maxCastPerTurn: number | null;
  maxStack: number | null;
  minCastInterval: number | null;
  minPlayerLevel: number | null;
  minRange: number;
  previewZones: string;
  range: number;
  spellBreed: number;
  spellId: number;
  statesCriterion: string | null;
}

export interface SpellPairs {
  descriptionId: number;
  iconId: number;
  id: number;
  nameId: number;
}

export interface Spells {
  adminName: string | null;
  basePreviewZoneDescr: string;
  boundScriptUsageData: string;
  criticalHitBoundScriptUsageData: string;
  descriptionId: number;
  iconId: number | null;
  id: number;
  m_flags: number;
  nameId: number;
  order: number | null;
  scriptId: number | null;
  scriptIdCritical: number | null;
  scriptParams: string | null;
  scriptParamsCritical: string | null;
  spellLevels: string;
  typeId: number;
}

export interface SpellScripts {
  id: string;
  rawParams: string;
  type: number;
}

export interface SpellStates {
  cantBeMoved: number | null;
  cantBePushed: number | null;
  cantBeTackled: number | null;
  cantDealDamage: number | null;
  cantSwitchPosition: number | null;
  cantTackle: number | null;
  displayTurnRemaining: number | null;
  icon: string | null;
  iconVisibilityMask: number | null;
  id: number;
  incurable: number | null;
  invulnerable: number | null;
  invulnerableMelee: number | null;
  invulnerableRange: number | null;
  isMainState: number | null;
  isSilent: number | null;
  nameId: number;
  preventsFight: number | null;
  preventsSpellCast: number | null;
}

export interface SpellStatesEffectsIdsJunction {
  SpellStates_id: number | null;
  target_id: number | null;
}

export interface SpellTypes {
  id: number;
  longNameId: string;
  shortNameId: string;
}

export interface SpellVariants {
  breedId: number;
  id: number;
}

export interface SpellVariantsSpellIdsJunction {
  SpellVariants_id: number | null;
  target_id: number | null;
}

export interface StealthBones {
  id: number;
}

export interface SubAreas {
  achievements: string;
  areaId: number | null;
  associatedZaapMapId: number;
  basicAccountAllowed: number | null;
  bounds: string;
  capturable: number;
  customWorldMap: string;
  displayOnWorldMap: number;
  exploreAchievementId: number | null;
  harvestables: string;
  id: number;
  isConquestVillage: number | null;
  level: number;
  monsters: string;
  mountAutoTripAllowed: number;
  nameId: number;
  neighbors: string;
  packId: number;
  psiAllowed: number;
  shape: string;
}

export interface SubAreasEntranceMapIdsJunction {
  SubAreas_id: number | null;
  target_id: number | null;
}

export interface SubAreasExitMapIdsJunction {
  SubAreas_id: number | null;
  target_id: number | null;
}

export interface SubAreasMapIdsJunction {
  SubAreas_id: number | null;
  target_id: number | null;
}

export interface Subhints {
  hintAnchor: number | null;
  hintAnchoredElement: string;
  hintCreationDate: number;
  hintHeight: number;
  hintHighlightedElement: string;
  hintId: number;
  hintOrder: number;
  hintParentUid: string;
  hintPositionX: number | null;
  hintPositionY: number | null;
  hintTooltipOffsetX: number;
  hintTooltipOffsetY: number;
  hintTooltipPositionEnum: number;
  hintTooltipText: string;
  hintTooltipUrl: string | null;
  hintTooltipWidth: number;
  hintWidth: number;
  id: string;
}

export interface SuperAreas {
  hasWorldMap: number;
  id: number;
  nameId: number;
  worldmapId: number;
}

export interface TaxCollectorFirstnames {
  firstnameId: string;
  id: number;
}

export interface TaxCollectorNames {
  id: number;
  nameId: number;
}

export interface TextIconReferences {
  gfxId: string;
  id: number;
  referenceKey: string;
}

export interface Tips {
  descId: string;
  id: number;
}

export interface TitleCategories {
  id: number;
  nameId: number;
}

export interface Titles {
  categoryId: number;
  id: number;
  nameFemaleId: string;
  nameMaleId: string;
  visible: number | null;
}

export interface Translations {
  id: string | null;
  lang: string | null;
  value: string | null;
}

export interface VeteranRewards {
  id: number;
  itemGID: number;
  itemQuantity: number;
  requiredSubDays: number;
}

export interface Waypoints {
  activated: number;
  id: number;
  mapId: number;
  subAreaId: number;
}

export interface Weapons {
  apCost: number;
  appearanceId: number | null;
  castInDiagonal: number | null;
  castInLine: number | null;
  castTestLos: number | null;
  changeVersion: string | null;
  craftConditional: string | null;
  craftFeasible: string;
  craftVisible: string;
  craftXpRatio: number;
  criteria: string | null;
  criteriaTarget: string | null;
  criticalFailureProbability: number | null;
  criticalHitBonus: number;
  criticalHitProbability: number;
  descriptionId: number;
  favoriteRecyclingSubareas: string;
  favoriteSubAreas: string;
  favoriteSubAreasBonus: number | null;
  iconId: number;
  id: number;
  importantNoticeId: string | null;
  isColorable: number | null;
  itemSetId: number;
  level: number;
  m_flags: number;
  maxCastPerTurn: number;
  minRange: number;
  nameId: number;
  possibleEffects: string;
  price: number;
  range: number;
  realWeight: number;
  recipeSlots: number;
  recyclingNuggets: number | null;
  resourcesBySubarea: string;
  tooltipExpirationDate: string;
  typeId: number;
  useAnimationId: number;
  visibility: string | null;
}

export interface WeaponsDropMonsterIdsJunction {
  target_id: number | null;
  Weapons_id: number | null;
}

export interface WeaponsDropTemporisMonsterIdsJunction {
  target_id: number | null;
  Weapons_id: number | null;
}

export interface WeaponsEvolutiveEffectIdsJunction {
  target_id: number | null;
  Weapons_id: number | null;
}

export interface WeaponsRecipeIdsJunction {
  target_id: number | null;
  Weapons_id: number | null;
}

export interface WorldEvents {
  areas: string;
  categoryId: number;
  deletedObjects: string;
  dungeonHunterGroupsPerMap: number;
  endMsgId: number;
  fightScenarios: string;
  globalDrops: string;
  id: number;
  monsterHunterGroupsPerMap: number;
  nameId: number;
  preMsgDelay: number;
  preMsgId: number;
  scoreMsgTiming: number;
  startMsgId: number;
  subareas: string;
}

export interface WorldMaps {
  id: number;
  mapHeight: number;
  mapWidth: number;
  maxScale: number;
  minScale: number;
  nameId: number;
  origineX: number;
  origineY: number;
  startScale: number;
  totalHeight: number;
  totalWidth: number;
  viewableEverywhere: number;
  visibleOnMap: number;
  zoom: string;
}

export interface DB {
  AbuseReasons: AbuseReasons;
  AchievementCategories: AchievementCategories;
  AchievementCategories_achievementIds_junction: AchievementCategoriesAchievementIdsJunction;
  AchievementObjectives: AchievementObjectives;
  AchievementProgress: AchievementProgress;
  AchievementProgressSteps: AchievementProgressSteps;
  AchievementRewards: AchievementRewards;
  Achievements: Achievements;
  Achievements_objectiveIds_junction: AchievementsObjectiveIdsJunction;
  Achievements_rewardIds_junction: AchievementsRewardIdsJunction;
  ActionFilters: ActionFilters;
  ActivitySuggestions: ActivitySuggestions;
  ActivitySuggestionsCategories: ActivitySuggestionsCategories;
  AlignmentGift: AlignmentGift;
  AlignmentOrder: AlignmentOrder;
  AlignmentRank: AlignmentRank;
  AlignmentRankJntGift: AlignmentRankJntGift;
  AlignmentSides: AlignmentSides;
  AlignmentTitles: AlignmentTitles;
  AllianceRankNameSuggestions: AllianceRankNameSuggestions;
  AllianceRanks: AllianceRanks;
  AllianceRightGroups: AllianceRightGroups;
  AllianceRights: AllianceRights;
  AllianceTags: AllianceTags;
  AllianceTagsTypes: AllianceTagsTypes;
  AlmanaxCalendars: AlmanaxCalendars;
  AlmanaxCalendars_bonusesIds_junction: AlmanaxCalendarsBonusesIdsJunction;
  AlterationCategories: AlterationCategories;
  Alterations: Alterations;
  Appearances: Appearances;
  Areas: Areas;
  ArenaLeagueRewards: ArenaLeagueRewards;
  ArenaLeagues: ArenaLeagues;
  ArenaLeagueSeasons: ArenaLeagueSeasons;
  Bonuses: Bonuses;
  Bonuses_criterionsIds_junction: BonusesCriterionsIdsJunction;
  BonusesAreaCriterion: BonusesAreaCriterion;
  BonusesCriterions: BonusesCriterions;
  BonusesEquippedItemCriterion: BonusesEquippedItemCriterion;
  BonusesMonsterCriterion: BonusesMonsterCriterion;
  BonusesMonsterFamilyCriterion: BonusesMonsterFamilyCriterion;
  BonusesQuestCategoryCriterion: BonusesQuestCategoryCriterion;
  BonusesSubAreaCriterion: BonusesSubAreaCriterion;
  BreachBosses: BreachBosses;
  BreachDungeonModificators: BreachDungeonModificators;
  BreachInfinityLevels: BreachInfinityLevels;
  BreachPrizes: BreachPrizes;
  BreachWorldMapCoordinates: BreachWorldMapCoordinates;
  BreachWorldMapSectors: BreachWorldMapSectors;
  BreedRoles: BreedRoles;
  Breeds: Breeds;
  CensoredContents: CensoredContents;
  CensoredWords: CensoredWords;
  Challenges: Challenges;
  CharacteristicCategories: CharacteristicCategories;
  CharacteristicCategories_characteristicIds_junction: CharacteristicCategoriesCharacteristicIdsJunction;
  Characteristics: Characteristics;
  CharacterXPMappings: CharacterXPMappings;
  ChatChannels: ChatChannels;
  Choices: Choices;
  Collectables: Collectables;
  Collections: Collections;
  CompanionCharacteristics: CompanionCharacteristics;
  Companions: Companions;
  CompanionSpells: CompanionSpells;
  CreatureBonesOverrides: CreatureBonesOverrides;
  CreatureBonesTypes: CreatureBonesTypes;
  CustomModeBreedSpells: CustomModeBreedSpells;
  Documents: Documents;
  Dungeons: Dungeons;
  Dungeons_mapIds_junction: DungeonsMapIdsJunction;
  EffectInstanceDice: EffectInstanceDice;
  Effects: Effects;
  EmblemBackgrounds: EmblemBackgrounds;
  EmblemSymbolCategories: EmblemSymbolCategories;
  EmblemSymbols: EmblemSymbols;
  Emoticons: Emoticons;
  EvolutiveEffects: EvolutiveEffects;
  EvolutiveItemTypes: EvolutiveItemTypes;
  ExpeditionSeasons: ExpeditionSeasons;
  ExternalNotifications: ExternalNotifications;
  FeatureDescriptions: FeatureDescriptions;
  FightScenarios: FightScenarios;
  FinishMoves: FinishMoves;
  ForgettableSpells: ForgettableSpells;
  GuildChestTabs: GuildChestTabs;
  GuildRankNameSuggestions: GuildRankNameSuggestions;
  GuildRanks: GuildRanks;
  GuildRightGroups: GuildRightGroups;
  GuildRights: GuildRights;
  GuildTags: GuildTags;
  GuildTagsTypes: GuildTagsTypes;
  HavenbagFurnitures: HavenbagFurnitures;
  HavenbagThemes: HavenbagThemes;
  Heads: Heads;
  HintCategory: HintCategory;
  Hints: Hints;
  Houses: Houses;
  IncarnationLevels: IncarnationLevels;
  InfoMessages: InfoMessages;
  Interactives: Interactives;
  Items: Items;
  Items_dropMonsterIds_junction: ItemsDropMonsterIdsJunction;
  Items_dropTemporisMonsterIds_junction: ItemsDropTemporisMonsterIdsJunction;
  Items_evolutiveEffectIds_junction: ItemsEvolutiveEffectIdsJunction;
  Items_recipeIds_junction: ItemsRecipeIdsJunction;
  ItemSets: ItemSets;
  ItemSuperTypes: ItemSuperTypes;
  ItemTypes: ItemTypes;
  Jobs: Jobs;
  KothRoles: KothRoles;
  LegendaryPowersCategories: LegendaryPowersCategories;
  LegendaryTreasureHunts: LegendaryTreasureHunts;
  LivingObjectSkinJntMood: LivingObjectSkinJntMood;
  LuaFormulas: LuaFormulas;
  MapCoordinates: MapCoordinates;
  MapCoordinates_mapIds_junction: MapCoordinatesMapIdsJunction;
  MapPositions: MapPositions;
  MapReferences: MapReferences;
  MapScrollActions: MapScrollActions;
  Modsters: Modsters;
  MonsterDropChanceBonus: MonsterDropChanceBonus;
  MonsterDropChanceBonus_criterionsIds_junction: MonsterDropChanceBonusCriterionsIdsJunction;
  MonsterMiniBoss: MonsterMiniBoss;
  MonsterRaces: MonsterRaces;
  Monsters: Monsters;
  MonsterSuperRaces: MonsterSuperRaces;
  MonsterXPBonus: MonsterXPBonus;
  MonsterXPBonus_criterionsIds_junction: MonsterXPBonusCriterionsIdsJunction;
  Months: Months;
  MountBehaviors: MountBehaviors;
  MountBones: MountBones;
  MountFamily: MountFamily;
  Mounts: Mounts;
  NamingRules: NamingRules;
  Notifications: Notifications;
  NpcActions: NpcActions;
  NpcMessages: NpcMessages;
  Npcs: Npcs;
  OptionalFeatures: OptionalFeatures;
  Ornaments: Ornaments;
  Pack: Pack;
  Playlists: Playlists;
  PointOfInterest: PointOfInterest;
  PointOfInterestCategory: PointOfInterestCategory;
  PopupInformations: PopupInformations;
  PresetIcons: PresetIcons;
  QuestCategory: QuestCategory;
  QuestCategory_questIds_junction: QuestCategoryQuestIdsJunction;
  QuestKamasBonus: QuestKamasBonus;
  QuestKamasBonus_criterionsIds_junction: QuestKamasBonusCriterionsIdsJunction;
  QuestObjectiveBringItemToNpc: QuestObjectiveBringItemToNpc;
  QuestObjectiveBringSoulToNpc: QuestObjectiveBringSoulToNpc;
  QuestObjectiveCraftItem: QuestObjectiveCraftItem;
  QuestObjectiveDiscoverMap: QuestObjectiveDiscoverMap;
  QuestObjectiveDiscoverSubArea: QuestObjectiveDiscoverSubArea;
  QuestObjectiveFightMonster: QuestObjectiveFightMonster;
  QuestObjectiveFightMonstersOnMap: QuestObjectiveFightMonstersOnMap;
  QuestObjectiveFreeForm: QuestObjectiveFreeForm;
  QuestObjectiveGoToNpc: QuestObjectiveGoToNpc;
  QuestObjectiveMultiFightMonster: QuestObjectiveMultiFightMonster;
  QuestObjectiveTypes: QuestObjectiveTypes;
  Quests: Quests;
  Quests_stepIds_junction: QuestsStepIdsJunction;
  QuestStepRewards: QuestStepRewards;
  QuestSteps: QuestSteps;
  QuestSteps_objectiveIds_junction: QuestStepsObjectiveIdsJunction;
  QuestSteps_rewardsIds_junction: QuestStepsRewardsIdsJunction;
  QuestXPBonus: QuestXPBonus;
  QuestXPBonus_criterionsIds_junction: QuestXPBonusCriterionsIdsJunction;
  RandomDropGroups: RandomDropGroups;
  Recipes: Recipes;
  Recipes_ingredientIds_junction: RecipesIngredientIdsJunction;
  RideFood: RideFood;
  ServerCommunities: ServerCommunities;
  ServerCommunities_supportedLangIds_junction: ServerCommunitiesSupportedLangIdsJunction;
  ServerGameTypes: ServerGameTypes;
  ServerLangs: ServerLangs;
  ServerPopulations: ServerPopulations;
  Servers: Servers;
  ServerSeasons: ServerSeasons;
  Signs: Signs;
  SkillNames: SkillNames;
  Skills: Skills;
  Skills_craftableItemIds_junction: SkillsCraftableItemIdsJunction;
  Skills_modifiableItemTypeIds_junction: SkillsModifiableItemTypeIdsJunction;
  SkinMappings: SkinMappings;
  SkinSlotsRules: SkinSlotsRules;
  SmileyCategories: SmileyCategories;
  SmileyPacks: SmileyPacks;
  Smileys: Smileys;
  SocialRights: SocialRights;
  SoundBones: SoundBones;
  SoundUi: SoundUi;
  SoundUiHook: SoundUiHook;
  SpeakingItemsText: SpeakingItemsText;
  SpeakingItemsTriggers: SpeakingItemsTriggers;
  SpeakingItemsTriggers_textIds_junction: SpeakingItemsTriggersTextIdsJunction;
  SpellBombs: SpellBombs;
  SpellConversions: SpellConversions;
  SpellLevels: SpellLevels;
  SpellPairs: SpellPairs;
  Spells: Spells;
  SpellScripts: SpellScripts;
  SpellStates: SpellStates;
  SpellStates_effectsIds_junction: SpellStatesEffectsIdsJunction;
  SpellTypes: SpellTypes;
  SpellVariants: SpellVariants;
  SpellVariants_spellIds_junction: SpellVariantsSpellIdsJunction;
  StealthBones: StealthBones;
  SubAreas: SubAreas;
  SubAreas_entranceMapIds_junction: SubAreasEntranceMapIdsJunction;
  SubAreas_exitMapIds_junction: SubAreasExitMapIdsJunction;
  SubAreas_mapIds_junction: SubAreasMapIdsJunction;
  Subhints: Subhints;
  SuperAreas: SuperAreas;
  TaxCollectorFirstnames: TaxCollectorFirstnames;
  TaxCollectorNames: TaxCollectorNames;
  TextIconReferences: TextIconReferences;
  Tips: Tips;
  TitleCategories: TitleCategories;
  Titles: Titles;
  translations: Translations;
  VeteranRewards: VeteranRewards;
  Waypoints: Waypoints;
  Weapons: Weapons;
  Weapons_dropMonsterIds_junction: WeaponsDropMonsterIdsJunction;
  Weapons_dropTemporisMonsterIds_junction: WeaponsDropTemporisMonsterIdsJunction;
  Weapons_evolutiveEffectIds_junction: WeaponsEvolutiveEffectIdsJunction;
  Weapons_recipeIds_junction: WeaponsRecipeIdsJunction;
  WorldEvents: WorldEvents;
  WorldMaps: WorldMaps;
}
