name: Extract data and release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  process-and-update:
    name: Extract and Process Game Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache npm global and pnpm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.APPDATA }}\npm-cache 
            ${{ env.HOME }}/.npm 
            parser/node_modules
            ${{ github.workspace }}/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('parser/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install cytrus-v6
        run: npm i -g cytrus-v6

      - name: Get current version
        id: version
        run: echo "version=$(cytrus-v6 version --game dofus --release dofus3)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: ./parser
        run: pnpm install --frozen-lockfile

      - name: Extract data with cytrus
        working-directory: ./parser
        run: cytrus-v6 download --game dofus --release dofus3 --output temp/ --select **/StreamingAssets/Content/Data/**/*.bundle

      - name: Parse files to JSON
        working-directory: ./parser
        run: pnpm extract
        env:
          INPUT_FOLDER: temp/
          OUTPUT_FOLDER: json/

      - name: Update database
        working-directory: ./parser
        run: pnpm db
        env:
          DATABASE_URL: ./dofus.sqlite
          JSON_FOLDER: json/

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.version.outputs.version }} \
            --title "Release ${{ steps.version.outputs.version }}" \
            --draft=false \
            --prerelease=false

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v${{ steps.version.outputs.version }} \
            parser/json/* \
            parser/dofus.sqlite
