name: Extract data and release

on:
  workflow_dispatch:

jobs:
  process-and-update:
    name: Extract and Process Game Data
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install cytrus-v6
        run: npm install -g cytrus-v6

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        working-directory: ./parser
        run: pnpm install

      - name: Extract data with cytrus
        run: cytrus-v6 download --release dofus3 --output temp/ --select **/StreamingAssets/Content/Data/**/*.bundle

      - name: Parse files to JSON
        working-directory: ./parser
        run: pnpm extract
        env:
          INPUT_FOLDER: temp/
          OUTPUT_FOLDER: json/

      - name: Update database
        working-directory: ./parser
        run: pnpm db
        env:
          DATABASE_URL: ./dofus.sqlite
          JSON_FOLDER: json/
