name: Check version and extract data
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Custom tag for the release"
        required: false
        type: string

permissions:
  contents: write

jobs:
  process-and-update:
    # if: needs.check-version.outputs.should_release == 'true'
    name: Extract and Process Game Data
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $isPrerelease = ""
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
              $isPrerelease = "--prerelease"
          }

          $notes = "Quick links:`n"
          $notes += "  - [dofus.sqlite](https://github.com/ledouxm/dofus-sqlite/releases/download/v${{ needs.check-version.outputs.release_tag }}/dofus.sqlite)`n"
          $notes += "  - [dofus.proto](https://github.com/ledouxm/dofus-sqlite/releases/download/v${{ needs.check-version.outputs.release_tag }}/dofus.proto)`n`n"
          $notes += "Release contains:`n`n"
          $notes += "- dofus.sqlite database file`n"
          $notes += "- i18n files`n"
          $notes += "- Dofus 3 data files (quests, achievements, mapPositions, )`n"
          $notes += "- Dofus obfuscated proto file`n`n"
          $notes += "This release is auto-generated."

          gh release create "v${{ needs.check-version.outputs.release_tag }}" --title "Release ${{ needs.check-version.outputs.release_tag }}" --notes "$notes" --draft=false $isPrerelease

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $files = Get-ChildItem -Path "parser/json" -File
          foreach ($file in $files) {
              gh release upload "v${{ needs.check-version.outputs.release_tag }}" $file.FullName
          }
          gh release upload "v${{ needs.check-version.outputs.release_tag }}" parser/dofus.sqlite
          gh release upload "v${{ needs.check-version.outputs.release_tag }}" parser/dofus.proto
