name: Test
on:
  workflow_dispatch:

jobs:
  test:
    name: Check Game Version
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install cytrus-v6 and download
        run: |
          npm i -g cytrus-v6@0.1.1
          cytrus-v6 download --game dofus --release dofus3 --output temp/ --select **/GameAssembly.dll --select **/global-metadata.dat

      - name: Run Il2CppDumper
        run: .\Il2CppDumper\Il2CppDumper.exe ".\parser\temp\GameAssembly.dll" ".\parser\temp\Dofus_Data\il2cpp_data\Metadata\global-metadata.dat"

      - name: Run protodec
        run: .\Il2CppDumper\protodec.exe .\Il2CppDumper\DummyDll .\output.proto --include-properties-without-non-user-code-attribute
