name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - feat/add-proto

jobs:
  test:
    name: Check Game Version
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache workflow state
        id: cache-state
        uses: actions/cache@v3
        with:
          path: |
            parser/temp
            Il2CppDumper/DummyDll
          key: ${{ runner.os }}-workflow-state-${{ hashFiles('parser/temp/**', 'Il2CppDumper/DummyDll/**') }}
          save-on-error: true

      - name: Setup and download (if cache miss)
        if: steps.cache-state.outputs.cache-hit != 'true'
        run: |
          dotnet --version
          npm i -g cytrus-v6@0.1.1
          cytrus-v6 download --game dofus --release dofus3 --output temp/ --select **/GameAssembly.dll --select **/global-metadata.dat

      - name: Set permissions
        run: |
          icacls ".\Il2CppDumper\Il2CppDumper.exe" /grant Everyone:F
          icacls ".\parser\temp\GameAssembly.dll" /grant Everyone:F
          icacls ".\parser\temp\Dofus_Data\il2cpp_data\Metadata\global-metadata.dat" /grant Everyone:F

      - name: Check environment
        run: |
          [Environment]::Is64BitOperatingSystem
          [Environment]::Is64BitProcess

      - name: Run Il2CppDumper
        run: .\Il2CppDumper\Il2CppDumper.exe .\parser\temp\GameAssembly.dll .\parser\temp\Dofus_Data\il2cpp_data\Metadata\global-metadata.dat
        shell: pwsh

      - name: Run protodec
        run: .\Il2CppDumper\protodec.exe .\Il2CppDumper\DummyDll .\output.proto --include-properties-without-non-user-code-attribute
